<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_Pais extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['codigo' => '013', 'pais' => 'AFGANISTAN'],
            ['codigo' => '017', 'pais' => 'ALBANIA'],
            ['codigo' => '023', 'pais' => 'ALEMANIA'],
            ['codigo' => '037', 'pais' => 'ANDORRA'],
            ['codigo' => '040', 'pais' => 'ANGOLA'],
            ['codigo' => '041', 'pais' => 'ANGUILLA'],
            ['codigo' => '043', 'pais' => 'ANTIGUA Y BARBUDA'],
            ['codigo' => '047', 'pais' => 'ANTILLAS HOLANDESAS'],
            ['codigo' => '053', 'pais' => 'ARABIA SAUDITA'],
            ['codigo' => '059', 'pais' => 'ARGELIA'],
            ['codigo' => '063', 'pais' => 'ARGENTINA'],
            ['codigo' => '026', 'pais' => 'ARMENIA'],
            ['codigo' => '027', 'pais' => 'ARUBA'],
            ['codigo' => '069', 'pais' => 'AUSTRALIA'],
            ['codigo' => '072', 'pais' => 'AUSTRIA'],
            ['codigo' => '074', 'pais' => 'AZERBAIJAN'],
            ['codigo' => '077', 'pais' => 'BAHAMAS'],
            ['codigo' => '080', 'pais' => 'BAHREIN'],
            ['codigo' => '081', 'pais' => 'BANGLADESH'],
            ['codigo' => '083', 'pais' => 'BARBADOS'],
            ['codigo' => '087', 'pais' => 'BELGICA'],
            ['codigo' => '088', 'pais' => 'BELICE'],
            ['codigo' => '091', 'pais' => 'BELORUS'],
            ['codigo' => '229', 'pais' => 'BENIN'],
            ['codigo' => '090', 'pais' => 'BERMUDAS'],
            ['codigo' => '093', 'pais' => 'BIRMANIA (MYANMAR)'],
            ['codigo' => '097', 'pais' => 'BOLIVIA'],
            ['codigo' => '029', 'pais' => 'BOSNIA-HERZEGOVINA'],
            ['codigo' => '101', 'pais' => 'BOTSWANA'],
            ['codigo' => '105', 'pais' => 'BRASIL'],
            ['codigo' => '108', 'pais' => 'BRUNEI DARUSSALAM'],
            ['codigo' => '111', 'pais' => 'BULGARIA'],
            ['codigo' => '031', 'pais' => 'BURKINA FASSO'],
            ['codigo' => '115', 'pais' => 'BURUNDI'],
            ['codigo' => '119', 'pais' => 'BUTAN'],
            ['codigo' => '127', 'pais' => 'CABO VERDE'],
            ['codigo' => '137', 'pais' => 'CAIMAN, ISLAS'],
            ['codigo' => '145', 'pais' => 'CAMERUN, REPUBLICA U'],
            ['codigo' => '149', 'pais' => 'CANADA'],
            ['codigo' => '155', 'pais' => 'CANAL(NORMANDAS),ISL'],
            ['codigo' => '157', 'pais' => 'CANTON ENDERBURY,ISL'],
            ['codigo' => '203', 'pais' => 'CHAD'],
            ['codigo' => '211', 'pais' => 'CHILE'],
            ['codigo' => '215', 'pais' => 'CHINA'],
            ['codigo' => '221', 'pais' => 'CHIPRE'],
            ['codigo' => '159', 'pais' => 'CIUDAD DEL VATICANO'],
            ['codigo' => '165', 'pais' => 'COCOS (KEELING), ISL'],
            ['codigo' => '169', 'pais' => 'COLOMBIA'],
            ['codigo' => '173', 'pais' => 'COMORAS'],
            ['codigo' => '998', 'pais' => 'COMUNIDAD EUROPEA'],
            ['codigo' => '177', 'pais' => 'CONGO'],
            ['codigo' => '183', 'pais' => 'COOK, ISLAS'],
            ['codigo' => '187', 'pais' => 'COREA DEL NORTE,REPU'],
            ['codigo' => '190', 'pais' => 'COREA DEL SUR, REPUB'],
            ['codigo' => '193', 'pais' => 'COSTA DE MARFIL'],
            ['codigo' => '196', 'pais' => 'COSTA RICA'],
            ['codigo' => '198', 'pais' => 'CROACIA'],
            ['codigo' => '199', 'pais' => 'CUBA'],
            ['codigo' => '789', 'pais' => 'CURACAO'],
            ['codigo' => '232', 'pais' => 'DINAMARCA'],
            ['codigo' => '783', 'pais' => 'DJIBOUTI'],
            ['codigo' => '235', 'pais' => 'DOMINICA'],
            ['codigo' => '239', 'pais' => 'ECUADOR'],
            ['codigo' => '240', 'pais' => 'EGIPTO'],
            ['codigo' => '242', 'pais' => 'EL SALVADOR'],
            ['codigo' => '244', 'pais' => 'EMIRATOS ARABES UNID'],
            ['codigo' => '243', 'pais' => 'ERITREA'],
            ['codigo' => '246', 'pais' => 'ESLOVAQUIA'],
            ['codigo' => '247', 'pais' => 'ESLOVENIA'],
            ['codigo' => '245', 'pais' => 'ESPAÑA'],
            ['codigo' => '249', 'pais' => 'ESTADOS UNIDOS'],
            ['codigo' => '251', 'pais' => 'ESTONIA'],
            ['codigo' => '253', 'pais' => 'ETIOPIA'],
            ['codigo' => '259', 'pais' => 'FEROE, ISLAS'],
            ['codigo' => '870', 'pais' => 'FIJI'],
            ['codigo' => '267', 'pais' => 'FILIPINAS'],
            ['codigo' => '271', 'pais' => 'FINLANDIA'],
            ['codigo' => '275', 'pais' => 'FRANCIA'],
            ['codigo' => '281', 'pais' => 'GABON'],
            ['codigo' => '285', 'pais' => 'GAMBIA'],
            ['codigo' => '286', 'pais' => 'GAZA Y JERICO'],
            ['codigo' => '287', 'pais' => 'GEORGIA'],
            ['codigo' => '289', 'pais' => 'GHANA'],
            ['codigo' => '293', 'pais' => 'GIBRALTAR'],
            ['codigo' => '297', 'pais' => 'GRANADA'],
            ['codigo' => '301', 'pais' => 'GRECIA'],
            ['codigo' => '305', 'pais' => 'GROENLANDIA'],
            ['codigo' => '309', 'pais' => 'GUADALUPE'],
            ['codigo' => '313', 'pais' => 'GUAM'],
            ['codigo' => '317', 'pais' => 'GUATEMALA'],
            ['codigo' => '325', 'pais' => 'GUAYANA FRANCESA'],
            ['codigo' => '329', 'pais' => 'GUINEA'],
            ['codigo' => '334', 'pais' => 'GUINEA - BISSAU'],
            ['codigo' => '331', 'pais' => 'GUINEA ECUATORIAL'],
            ['codigo' => '337', 'pais' => 'GUYANA'],
            ['codigo' => '341', 'pais' => 'HAITI'],
            ['codigo' => '345', 'pais' => 'HONDURAS'],
            ['codigo' => '351', 'pais' => 'HONG KONG'],
            ['codigo' => '355', 'pais' => 'HUNGRIA'],
            ['codigo' => '361', 'pais' => 'INDIA'],
            ['codigo' => '365', 'pais' => 'INDONESIA'],
            ['codigo' => '369', 'pais' => 'IRAK'],
            ['codigo' => '372', 'pais' => 'IRAN, REPUBLICA ISLA'],
            ['codigo' => '375', 'pais' => 'IRLANDA (EIRE)'],
            ['codigo' => '033', 'pais' => 'ISLA DE MAN'],
            ['codigo' => '379', 'pais' => 'ISLANDIA'],
            ['codigo' => '566', 'pais' => 'ISLAS MENORES DE ESTADOS UNIDOS'],
            ['codigo' => '383', 'pais' => 'ISRAEL'],
            ['codigo' => '386', 'pais' => 'ITALIA'],
            ['codigo' => '391', 'pais' => 'JAMAICA'],
            ['codigo' => '399', 'pais' => 'JAPON'],
            ['codigo' => '395', 'pais' => 'JOHNSTON,ISLA'],
            ['codigo' => '403', 'pais' => 'JORDANIA'],
            ['codigo' => '141', 'pais' => 'KAMPUCHEA (CAMBOYA)'],
            ['codigo' => '406', 'pais' => 'KAZAJSTAN'],
            ['codigo' => '410', 'pais' => 'KENYA'],
            ['codigo' => '412', 'pais' => 'KIRGUIZISTAN'],
            ['codigo' => '411', 'pais' => 'KIRIBATI'],
            ['codigo' => '413', 'pais' => 'KUWAIT'],
            ['codigo' => '420', 'pais' => 'LAOS,REPUBLICA POPUL'],
            ['codigo' => '426', 'pais' => 'LESOTHO'],
            ['codigo' => '429', 'pais' => 'LETONIA'],
            ['codigo' => '431', 'pais' => 'LIBANO'],
            ['codigo' => '434', 'pais' => 'LIBERIA'],
            ['codigo' => '438', 'pais' => 'LIBIA(INCLUYE FEZZAN'],
            ['codigo' => '440', 'pais' => 'LIECHTENSTEIN'],
            ['codigo' => '443', 'pais' => 'LITUANIA'],
            ['codigo' => '445', 'pais' => 'LUXEMBURGO'],
            ['codigo' => '447', 'pais' => 'MACAO'],
            ['codigo' => '448', 'pais' => 'MACEDONIA'],
            ['codigo' => '450', 'pais' => 'MADAGASCAR'],
            ['codigo' => '455', 'pais' => 'MALASIA'],
            ['codigo' => '458', 'pais' => 'MALAWI'],
            ['codigo' => '461', 'pais' => 'MALDIVAS'],
            ['codigo' => '464', 'pais' => 'MALI'],
            ['codigo' => '467', 'pais' => 'MALTA'],
            ['codigo' => '469', 'pais' => 'MARIANAS DEL NORTE,I'],
            ['codigo' => '474', 'pais' => 'MARRUECOS'],
            ['codigo' => '472', 'pais' => 'MARSHALL, ISLAS'],
            ['codigo' => '477', 'pais' => 'MARTINICA'],
            ['codigo' => '485', 'pais' => 'MAURICIO'],
            ['codigo' => '488', 'pais' => 'MAURITANIA'],
            ['codigo' => '493', 'pais' => 'MEXICO'],
            ['codigo' => '494', 'pais' => 'MICRONESIA,ESTADOS F'],
            ['codigo' => '495', 'pais' => 'MIDWAY, ISLAS'],
            ['codigo' => '496', 'pais' => 'MOLDAVIA'],
            ['codigo' => '498', 'pais' => 'MONACO'],
            ['codigo' => '497', 'pais' => 'MONGOLIA'],
            ['codigo' => '501', 'pais' => 'MONSERRAT, ISLA'],
            ['codigo' => '502', 'pais' => 'MONTENEGRO'],
            ['codigo' => '505', 'pais' => 'MOZAMBIQUE'],
            ['codigo' => '507', 'pais' => 'NAMIBIA'],
            ['codigo' => '508', 'pais' => 'NAURU'],
            ['codigo' => '511', 'pais' => 'NAVIDAD (CHRISTMAS)'],
            ['codigo' => '517', 'pais' => 'NEPAL'],
            ['codigo' => '521', 'pais' => 'NICARAGUA'],
            ['codigo' => '525', 'pais' => 'NIGER'],
            ['codigo' => '528', 'pais' => 'NIGERIA'],
            ['codigo' => '531', 'pais' => 'NIUE, ISLA'],
            ['codigo' => '001', 'pais' => 'NIVE ISLA'],
            ['codigo' => '999', 'pais' => 'NO DECLARADOS'],
            ['codigo' => '535', 'pais' => 'NORFOLK, ISLA'],
            ['codigo' => '538', 'pais' => 'NORUEGA'],
            ['codigo' => '542', 'pais' => 'NUEVA CALEDONIA'],
            ['codigo' => '548', 'pais' => 'NUEVA ZELANDIA'],
            ['codigo' => '556', 'pais' => 'OMAN'],
            ['codigo' => '573', 'pais' => 'PAISES BAJOS(HOLANDA'],
            ['codigo' => '576', 'pais' => 'PAKISTAN'],
            ['codigo' => '578', 'pais' => 'PALAU, ISLAS'],
            ['codigo' => '579', 'pais' => 'PALESTINA'],
            ['codigo' => '580', 'pais' => 'PANAMA'],
            ['codigo' => '545', 'pais' => 'PAPUASIA NUEV GUINEA'],
            ['codigo' => '586', 'pais' => 'PARAGUAY'],
            ['codigo' => '589', 'pais' => 'PERU'],
            ['codigo' => '593', 'pais' => 'PITCAIRN, ISLA'],
            ['codigo' => '599', 'pais' => 'POLINESIA FRANCESA'],
            ['codigo' => '603', 'pais' => 'POLONIA'],
            ['codigo' => '607', 'pais' => 'PORTUGAL'],
            ['codigo' => '611', 'pais' => 'PUERTO RICO'],
            ['codigo' => '618', 'pais' => 'QATAR'],
            ['codigo' => '628', 'pais' => 'REINO UNIDO'],
            ['codigo' => '640', 'pais' => 'REPUBLICA CENTROAFRI'],
            ['codigo' => '644', 'pais' => 'REPUBLICA CHECA'],
            ['codigo' => '888', 'pais' => 'REPUBLICA DEMOCRATICA DEL CONGO'],
            ['codigo' => '647', 'pais' => 'REPUBLICA DOMINICANA'],
            ['codigo' => '660', 'pais' => 'REUNION'],
            ['codigo' => '670', 'pais' => 'RUMANIA'],
            ['codigo' => '676', 'pais' => 'RUSIA'],
            ['codigo' => '675', 'pais' => 'RWANDA'],
            ['codigo' => '685', 'pais' => 'SAHARA OCCIDENTAL'],
            ['codigo' => '677', 'pais' => 'SALOMSN, ISLAS'],
            ['codigo' => '687', 'pais' => 'SAMOA'],
            ['codigo' => '690', 'pais' => 'SAMOA NORTEAMERICANA'],
            ['codigo' => '695', 'pais' => 'SAN CRISTOBAL Y NIEVES'],
            ['codigo' => '697', 'pais' => 'SAN MARINO'],
            ['codigo' => '700', 'pais' => 'SAN PEDRO Y MIGUELON'],
            ['codigo' => '705', 'pais' => 'SAN VICENTE Y LAS GR'],
            ['codigo' => '710', 'pais' => 'SANTA ELENA'],
            ['codigo' => '715', 'pais' => 'SANTA LUCIA'],
            ['codigo' => '720', 'pais' => 'SANTO TOME Y PRINCIP'],
            ['codigo' => '728', 'pais' => 'SENEGAL'],
            ['codigo' => '032', 'pais' => 'SERBIA'],
            ['codigo' => '731', 'pais' => 'SEYCHELLES'],
            ['codigo' => '735', 'pais' => 'SIERRA LEONA'],
            ['codigo' => '741', 'pais' => 'SINGAPUR'],
            ['codigo' => '744', 'pais' => 'SIRIA,REPUBLICA ARAB'],
            ['codigo' => '748', 'pais' => 'SOMALIA'],
            ['codigo' => '750', 'pais' => 'SRI LANKA'],
            ['codigo' => '756', 'pais' => 'SUDAFRICA,REPUBLICA'],
            ['codigo' => '759', 'pais' => 'SUDAN'],
            ['codigo' => '764', 'pais' => 'SUECIA'],
            ['codigo' => '767', 'pais' => 'SUIZA'],
            ['codigo' => '770', 'pais' => 'SURINAM'],
            ['codigo' => '773', 'pais' => 'SWAZILANDIA'],
            ['codigo' => '774', 'pais' => 'TADJIKISTAN'],
            ['codigo' => '776', 'pais' => 'TAILANDIA'],
            ['codigo' => '218', 'pais' => 'TAIWAN (FORMOSA)'],
            ['codigo' => '780', 'pais' => 'TANZANIA,REPUBLICA U'],
            ['codigo' => '786', 'pais' => 'TERRI ANTARTICO BRIT'],
            ['codigo' => '787', 'pais' => 'TERRITORI BRITANICO'],
            ['codigo' => '788', 'pais' => 'TIMOR DEL ESTE'],
            ['codigo' => '800', 'pais' => 'TOGO'],
            ['codigo' => '805', 'pais' => 'TOKELAU'],
            ['codigo' => '810', 'pais' => 'TONGA'],
            ['codigo' => '815', 'pais' => 'TRINIDAD Y TOBAGO'],
            ['codigo' => '820', 'pais' => 'TUNICIA'],
            ['codigo' => '823', 'pais' => 'TURCAS Y CAICOS,ISLA'],
            ['codigo' => '825', 'pais' => 'TURKMENISTAN'],
            ['codigo' => '827', 'pais' => 'TURQUIA'],
            ['codigo' => '828', 'pais' => 'TUVALU'],
            ['codigo' => '830', 'pais' => 'UCRANIA'],
            ['codigo' => '833', 'pais' => 'UGANDA'],
            ['codigo' => '845', 'pais' => 'URUGUAY'],
            ['codigo' => '847', 'pais' => 'UZBEKISTAN'],
            ['codigo' => '551', 'pais' => 'VANUATU'],
            ['codigo' => '850', 'pais' => 'VENEZUELA'],
            ['codigo' => '855', 'pais' => 'VIETNAM'],
            ['codigo' => '863', 'pais' => 'VIRGENES,ISLAS(BRITA'],
            ['codigo' => '866', 'pais' => 'VIRGENES,ISLAS(NORTE'],
            ['codigo' => '875', 'pais' => 'WALLIS Y FORTUNA,ISL'],
            ['codigo' => '880', 'pais' => 'YEMEN'],
            ['codigo' => '885', 'pais' => 'YUGOSLAVIA'],
            ['codigo' => '890', 'pais' => 'ZAMBIA'],
            ['codigo' => '665', 'pais' => 'ZIMBABWE'],
            ['codigo' => '895', 'pais' => 'ZONA CANAL DE PANAMA'],
            ['codigo' => '897', 'pais' => 'ZONA NEUTRAL(PALESTA'],


        ];
        foreach ($paises as $item) {
            DB::table('pais')->insert([
                'codigo' => $item['codigo'],
                'pais' => utf8_decode(utf8_encode($item['pais'])),
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
