<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_Circuitos extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $areas = [
            ['distrito_id' => 2, 'circuito' => 'ABEJORRAL'],
            ['distrito_id' => 60, 'circuito' => 'ACACÍAS'],
            ['distrito_id' => 59, 'circuito' => 'AGUACHICA'],
            ['distrito_id' => 33, 'circuito' => 'AGUADAS'],
            ['distrito_id' => 1, 'circuito' => 'ALTAS CORTES'],
            ['distrito_id' => 2, 'circuito' => 'AMAGÁ'],
            ['distrito_id' => 2, 'circuito' => 'AMALFI'],
            ['distrito_id' => 2, 'circuito' => 'ANDES'],
            ['distrito_id' => 33, 'circuito' => 'ANSERMA'],
            ['distrito_id' => 2, 'circuito' => 'ANTIOQUIA'],
            ['distrito_id' => 2, 'circuito' => 'ANTIOQUIA (O)'],
            ['distrito_id' => 2, 'circuito' => 'APARTADÓ '],
            ['distrito_id' => 43, 'circuito' => 'APÍA'],
            ['distrito_id' => 3, 'circuito' => 'ARAUCA'],
            ['distrito_id' => 4, 'circuito' => 'ARMENIA'],
            ['distrito_id' => 5, 'circuito' => 'ATLÁNTICO'],
            ['distrito_id' => 37, 'circuito' => 'AYAPEL'],
            ['distrito_id' => 45, 'circuito' => 'BAHÍA SOLANO'],
            ['distrito_id' => 42, 'circuito' => 'BARBACOAS'],
            ['distrito_id' => 10, 'circuito' => 'BARRANCABERMEJA'],
            ['distrito_id' => 6, 'circuito' => 'BARRANQUILLA'],
            ['distrito_id' => 27, 'circuito' => 'BELÉN DE LOS ANDAQUÍES'],
            ['distrito_id' => 43, 'circuito' => 'BELÉN DE UMBRÍA'],
            ['distrito_id' => 34, 'circuito' => 'BELLO'],
            ['distrito_id' => 7, 'circuito' => 'BOGOTÁ'],
            ['distrito_id' => 26, 'circuito' => 'BOGOTÁ(C)'],
            ['distrito_id' => 2, 'circuito' => 'BOLÍVAR'],
            ['distrito_id' => 9, 'circuito' => 'BOYACÁ'],
            ['distrito_id' => 10, 'circuito' => 'BUCARAMANGA'],
            ['distrito_id' => 11, 'circuito' => 'BUENAVENTURA'],
            ['distrito_id' => 11, 'circuito' => 'BUGA'],
            ['distrito_id' => 4, 'circuito' => 'CALARCÁ'],
            ['distrito_id' => 34, 'circuito' => 'CALDAS'],
            ['distrito_id' => 13, 'circuito' => 'CALI'],
            ['distrito_id' => 44, 'circuito' => 'CALOTO'],
            ['distrito_id' => 14, 'circuito' => 'CAQUETÁ'],
            ['distrito_id' => 26, 'circuito' => 'CÁQUEZA'],
            ['distrito_id' => 15, 'circuito' => 'CARMEN DE BOLÍVAR'],
            ['distrito_id' => 15, 'circuito' => 'CARTAGENA'],
            ['distrito_id' => 11, 'circuito' => 'CARTAGO'],
            ['distrito_id' => 17, 'circuito' => 'CAUCA'],
            ['distrito_id' => 2, 'circuito' => 'CAUCASIA'],
            ['distrito_id' => 37, 'circuito' => 'CERETÉ'],
            ['distrito_id' => 19, 'circuito' => 'CESAR'],
            ['distrito_id' => 30, 'circuito' => 'CHAPARRAL'],
            ['distrito_id' => 50, 'circuito' => 'CHARALÁ'],
            ['distrito_id' => 33, 'circuito' => 'CHINCHINÁ'],
            ['distrito_id' => 37, 'circuito' => 'CHINÚ'],
            ['distrito_id' => 57, 'circuito' => 'CHIQUINQUIRÁ'],
            ['distrito_id' => 59, 'circuito' => 'CHIRIGUANÁ'],
            ['distrito_id' => 20, 'circuito' => 'CHOCÓ'],
            ['distrito_id' => 26, 'circuito' => 'CHOCONTÁ'],
            ['distrito_id' => 51, 'circuito' => 'CIÉNAGA'],
            ['distrito_id' => 50, 'circuito' => 'CIMITARRA'],
            ['distrito_id' => 2, 'circuito' => 'CISNEROS'],
            ['distrito_id' => 2, 'circuito' => 'CONCORDIA'],
            ['distrito_id' => 22, 'circuito' => 'CÓRDOBA'],
            ['distrito_id' => 54, 'circuito' => 'COROZAL'],
            ['distrito_id' => 25, 'circuito' => 'CÚCUTA'],
            ['distrito_id' => 26, 'circuito' => 'CUNDINAMARCA'],
            ['distrito_id' => 2, 'circuito' => 'DABEIBA'],
            ['distrito_id' => 43, 'circuito' => 'DOSQUEBRADAS'],
            ['distrito_id' => 52, 'circuito' => 'DUITAMA'],
            ['distrito_id' => 2, 'circuito' => 'EL BAGRE'],
            ['distrito_id' => 51, 'circuito' => 'EL BANCO'],
            ['distrito_id' => 52, 'circuito' => 'EL COCUY'],
            ['distrito_id' => 2, 'circuito' => 'EL SANTUARIO'],
            ['distrito_id' => 34, 'circuito' => 'ENVIGADO'],
            ['distrito_id' => 30, 'circuito' => 'ESPINAL'],
            ['distrito_id' => 26, 'circuito' => 'FACATATIVÁ'],
            ['distrito_id' => 27, 'circuito' => 'FLORENCIA'],
            ['distrito_id' => 2, 'circuito' => 'FREDONIA'],
            ['distrito_id' => 30, 'circuito' => 'FRESNO'],
            ['distrito_id' => 2, 'circuito' => 'FRONTINO'],
            ['distrito_id' => 51, 'circuito' => 'FUNDACIÓN'],
            ['distrito_id' => 26, 'circuito' => 'FUNZA'],
            ['distrito_id' => 26, 'circuito' => 'FUSAGASUGÁ'],
            ['distrito_id' => 26, 'circuito' => 'GACHETÁ'],
            ['distrito_id' => 57, 'circuito' => 'GARAGOA'],
            ['distrito_id' => 39, 'circuito' => 'GARZÓN'],
            ['distrito_id' => 26, 'circuito' => 'GIRARDOT'],
            ['distrito_id' => 34, 'circuito' => 'GIRARDOTA'],
            ['distrito_id' => 60, 'circuito' => 'GRANADA'],
            ['distrito_id' => 26, 'circuito' => 'GUADUAS'],
            ['distrito_id' => 30, 'circuito' => 'GUAMO'],
            ['distrito_id' => 44, 'circuito' => 'GUAPÍ '],
            ['distrito_id' => 57, 'circuito' => 'GUATEQUE'],
            ['distrito_id' => 30, 'circuito' => 'HONDA'],
            ['distrito_id' => 29, 'circuito' => 'HUILA'],
            ['distrito_id' => 30, 'circuito' => 'IBAGUÉ'],
            ['distrito_id' => 42, 'circuito' => 'IPIALES'],
            ['distrito_id' => 45, 'circuito' => 'ISTMINA'],
            ['distrito_id' => 34, 'circuito' => 'ITAGÜI'],
            ['distrito_id' => 2, 'circuito' => 'ITUANGO'],
            ['distrito_id' => 2, 'circuito' => 'JERICÓ'],
            ['distrito_id' => 2, 'circuito' => 'LA CEJA'],
            ['distrito_id' => 42, 'circuito' => 'LA CRUZ'],
            ['distrito_id' => 33, 'circuito' => 'LA DORADA'],
            ['distrito_id' => 31, 'circuito' => 'LA GUAJIRA'],
            ['distrito_id' => 26, 'circuito' => 'LA MESA'],
            ['distrito_id' => 26, 'circuito' => 'LA PALMA'],
            ['distrito_id' => 39, 'circuito' => 'LA PLATA'],
            ['distrito_id' => 42, 'circuito' => 'LA UNIÓN'],
            ['distrito_id' => 43, 'circuito' => 'LA VIRGINIA'],
            ['distrito_id' => 30, 'circuito' => 'LÉRIDA'],
            ['distrito_id' => 26, 'circuito' => 'LETICIA'],
            ['distrito_id' => 30, 'circuito' => 'LÍBANO'],
            ['distrito_id' => 37, 'circuito' => 'LORICA'],
            ['distrito_id' => 25, 'circuito' => 'LOS PATIOS'],
            ['distrito_id' => 15, 'circuito' => 'MAGANGUÉ'],
            ['distrito_id' => 32, 'circuito' => 'MAGDALENA'],
            ['distrito_id' => 47, 'circuito' => 'MAICAO'],
            ['distrito_id' => 54, 'circuito' => 'MAJAGUAL'],
            ['distrito_id' => 10, 'circuito' => 'MÁLAGA'],
            ['distrito_id' => 33, 'circuito' => 'MANIZALES'],
            ['distrito_id' => 33, 'circuito' => 'MANZANARES'],
            ['distrito_id' => 2, 'circuito' => 'MARINILLA'],
            ['distrito_id' => 34, 'circuito' => 'MEDELLÍN'],
            ['distrito_id' => 30, 'circuito' => 'MELGAR'],
            ['distrito_id' => 35, 'circuito' => 'META'],
            ['distrito_id' => 57, 'circuito' => 'MIRAFLORES'],
            ['distrito_id' => 60, 'circuito' => 'MITÚ'],
            ['distrito_id' => 36, 'circuito' => 'MOCOA'],
            ['distrito_id' => 15, 'circuito' => 'MOMPÓS'],
            ['distrito_id' => 57, 'circuito' => 'MONIQUIRÁ'],
            ['distrito_id' => 37, 'circuito' => 'MONTELÍBANO'],
            ['distrito_id' => 37, 'circuito' => 'MONTERÍA'],
            ['distrito_id' => 61, 'circuito' => 'MONTERREY'],
            ['distrito_id' => 38, 'circuito' => 'NARIÑO'],
            ['distrito_id' => 39, 'circuito' => 'NEIVA'],
            ['distrito_id' => 40, 'circuito' => 'NORTE DE SANTANDER'],
            ['distrito_id' => 25, 'circuito' => 'OCAÑA'],
            ['distrito_id' => 61, 'circuito' => 'OROCUÉ'],
            ['distrito_id' => 26, 'circuito' => 'PACHO'],
            ['distrito_id' => 11, 'circuito' => 'PALMIRA'],
            ['distrito_id' => 41, 'circuito' => 'PAMPLONA'],
            ['distrito_id' => 42, 'circuito' => 'PASTO'],
            ['distrito_id' => 44, 'circuito' => 'PATÍA - EL BORDO'],
            ['distrito_id' => 61, 'circuito' => 'PAZ DE ARIPORO'],
            ['distrito_id' => 52, 'circuito' => 'PAZ DEL RIO'],
            ['distrito_id' => 33, 'circuito' => 'PENSILVANIA'],
            ['distrito_id' => 43, 'circuito' => 'PEREIRA'],
            ['distrito_id' => 39, 'circuito' => 'PITALITO'],
            ['distrito_id' => 51, 'circuito' => 'PIVIJAY'],
            ['distrito_id' => 37, 'circuito' => 'PLANETA RICA'],
            ['distrito_id' => 51, 'circuito' => 'PLATO'],
            ['distrito_id' => 44, 'circuito' => 'POPAYÁN'],
            ['distrito_id' => 50, 'circuito' => 'PUENTE NACIONAL'],
            ['distrito_id' => 2, 'circuito' => 'PUERTO BERRIO'],
            ['distrito_id' => 33, 'circuito' => 'PUERTO BOYACÁ'],
            ['distrito_id' => 60, 'circuito' => 'PUERTO CARREÑO'],
            ['distrito_id' => 60, 'circuito' => 'PUERTO INÍRIDA'],
            ['distrito_id' => 60, 'circuito' => 'PUERTO LÓPEZ'],
            ['distrito_id' => 27, 'circuito' => 'PUERTO RICO'],
            ['distrito_id' => 44, 'circuito' => 'PUERTO TEJADA'],
            ['distrito_id' => 36, 'circuito' => 'PUETO ASÍS'],
            ['distrito_id' => 30, 'circuito' => 'PURIFICACIÓN'],
            ['distrito_id' => 45, 'circuito' => 'QUIBDÓ'],
            ['distrito_id' => 43, 'circuito' => 'QUINCHÍA'],
            ['distrito_id' => 46, 'circuito' => 'QUINDÍO'],
            ['distrito_id' => 57, 'circuito' => 'RAMIRIQUÍ'],
            ['distrito_id' => 47, 'circuito' => 'RIOHACHA'],
            ['distrito_id' => 2, 'circuito' => 'RIONEGRO '],
            ['distrito_id' => 33, 'circuito' => 'RIOSUCIO'],
            ['distrito_id' => 48, 'circuito' => 'RISARALDA'],
            ['distrito_id' => 11, 'circuito' => 'ROLDANILLO'],
            ['distrito_id' => 6, 'circuito' => 'SABANALARGA'],
            ['distrito_id' => 37, 'circuito' => 'SAHAGÚN'],
            ['distrito_id' => 33, 'circuito' => 'SALAMINA'],
            ['distrito_id' => 42, 'circuito' => 'SAMANIEGO'],
            ['distrito_id' => 49, 'circuito' => 'SAN ANDRÉS'],
            ['distrito_id' => 50, 'circuito' => 'SAN GIL'],
            ['distrito_id' => 60, 'circuito' => 'SAN JOSÉ DEL GUAVIARE'],
            ['distrito_id' => 47, 'circuito' => 'SAN JUAN DEL CESAR'],
            ['distrito_id' => 54, 'circuito' => 'SAN MARCOS'],
            ['distrito_id' => 60, 'circuito' => 'SAN MARTÍN'],
            ['distrito_id' => 2, 'circuito' => 'SAN PEDRO DE LOS MILAGROS'],
            ['distrito_id' => 10, 'circuito' => 'SAN VICENTE DE CHUCURÍ'],
            ['distrito_id' => 2, 'circuito' => 'SANTA BÁRBARA '],
            ['distrito_id' => 2, 'circuito' => 'SANTA FE DE ANTIOQUIA'],
            ['distrito_id' => 51, 'circuito' => 'SANTA MARTA'],
            ['distrito_id' => 43, 'circuito' => 'SANTA ROSA DE CABAL '],
            ['distrito_id' => 2, 'circuito' => 'SANTA ROSA DE OSOS'],
            ['distrito_id' => 52, 'circuito' => 'SANTA ROSA DE VITERBO'],
            ['distrito_id' => 53, 'circuito' => 'SANTANDER'],
            ['distrito_id' => 44, 'circuito' => 'SANTANDER DE QUILICHAO'],
            ['distrito_id' => 3, 'circuito' => 'SARAVENA'],
            ['distrito_id' => 2, 'circuito' => 'SEGOVIA'],
            ['distrito_id' => 11, 'circuito' => 'SEVILLA'],
            ['distrito_id' => 36, 'circuito' => 'SIBUNDOY'],
            ['distrito_id' => 44, 'circuito' => 'SILVIA'],
            ['distrito_id' => 15, 'circuito' => 'SIMITÍ'],
            ['distrito_id' => 54, 'circuito' => 'SINCÉ'],
            ['distrito_id' => 54, 'circuito' => 'SINCELEJO'],
            ['distrito_id' => 26, 'circuito' => 'SOACHA'],
            ['distrito_id' => 52, 'circuito' => 'SOATÁ'],
            ['distrito_id' => 52, 'circuito' => 'SOCHA'],
            ['distrito_id' => 50, 'circuito' => 'SOCORRO'],
            ['distrito_id' => 52, 'circuito' => 'SOGAMOSO'],
            ['distrito_id' => 6, 'circuito' => 'SOLEDAD'],
            ['distrito_id' => 2, 'circuito' => 'SONSÓN'],
            ['distrito_id' => 2, 'circuito' => 'SOPETRÁN'],
            ['distrito_id' => 55, 'circuito' => 'SUCRE'],
            ['distrito_id' => 2, 'circuito' => 'TÁMESIS'],
            ['distrito_id' => 2, 'circuito' => 'TITIRIBÍ'],
            ['distrito_id' => 56, 'circuito' => 'TOLIMA'],
            ['distrito_id' => 11, 'circuito' => 'TULÚA'],
            ['distrito_id' => 42, 'circuito' => 'TUMACO'],
            ['distrito_id' => 57, 'circuito' => 'TUNJA'],
            ['distrito_id' => 42, 'circuito' => 'TÚQUERRES'],
            ['distrito_id' => 15, 'circuito' => 'TURBACO'],
            ['distrito_id' => 2, 'circuito' => 'TURBO'],
            ['distrito_id' => 26, 'circuito' => 'UBATÉ'],
            ['distrito_id' => 2, 'circuito' => 'URRAO'],
            ['distrito_id' => 58, 'circuito' => 'VALLE DEL CAUCA'],
            ['distrito_id' => 59, 'circuito' => 'VALLEDUPAR'],
            ['distrito_id' => 50, 'circuito' => 'VÉLEZ'],
            ['distrito_id' => 47, 'circuito' => 'VILLANUEVA'],
            ['distrito_id' => 60, 'circuito' => 'VILLAVICENCIO'],
            ['distrito_id' => 26, 'circuito' => 'VILLETA'],
            ['distrito_id' => 2, 'circuito' => 'YARUMAL'],
            ['distrito_id' => 2, 'circuito' => 'YOLOMBÓ'],
            ['distrito_id' => 61, 'circuito' => 'YOPAL'],
            ['distrito_id' => 26, 'circuito' => 'ZIPAQUIRÁ']
        ];
        foreach ($areas as $item) {
            DB::table('circuitos')->insert([
                'distrito_id' => $item['distrito_id'],
                'circuito' => $item['circuito'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
