<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Tabla_JuzgMunicipios extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $areas = [
            ['circuito_id' => 1, 'municipio' => 'ABEJORRAL'],
            ['circuito_id' => 132, 'municipio' => 'ABREGO'],
            ['circuito_id' => 74, 'municipio' => 'ABRIAQUÍ'],
            ['circuito_id' => 2, 'municipio' => 'ACACÍAS'],
            ['circuito_id' => 164, 'municipio' => 'ACANDÍ'],
            ['circuito_id' => 143, 'municipio' => 'ACEVEDO'],
            ['circuito_id' => 110, 'municipio' => 'ACHÍ'],
            ['circuito_id' => 80, 'municipio' => 'AGRADO'],
            ['circuito_id' => 81, 'municipio' => 'AGUA DE DIOS'],
            ['circuito_id' => 3, 'municipio' => 'AGUACHICA'],
            ['circuito_id' => 198, 'municipio' => 'AGUADA'],
            ['circuito_id' => 4, 'municipio' => 'AGUADAS'],
            ['circuito_id' => 223, 'municipio' => 'AGUAZUL'],
            ['circuito_id' => 216, 'municipio' => 'AGUSTÍN CODAZZI'],
            ['circuito_id' => 130, 'municipio' => 'AIPE'],
            ['circuito_id' => 70, 'municipio' => 'ALBÁN'],
            ['circuito_id' => 97, 'municipio' => 'ALBÁN SAN JOSÉ'],
            ['circuito_id' => 22, 'municipio' => 'ALBANIA'],
            ['circuito_id' => 40, 'municipio' => 'ALCALÁ'],
            ['circuito_id' => 91, 'municipio' => 'ALDANA'],
            ['circuito_id' => 163, 'municipio' => 'ALEJANDRÍA'],
            ['circuito_id' => 75, 'municipio' => 'ALGARROBO'],
            ['circuito_id' => 130, 'municipio' => 'ALGECIRAS'],
            ['circuito_id' => 27, 'municipio' => 'ALMAGUER'],
            ['circuito_id' => 87, 'municipio' => 'ALMEIDA'],
            ['circuito_id' => 157, 'municipio' => 'ALPUJARRA'],
            ['circuito_id' => 80, 'municipio' => 'ALTAMIRA'],
            ['circuito_id' => 92, 'municipio' => 'ALTO BAUDÓ'],
            ['circuito_id' => 124, 'municipio' => 'ALTOS DEL ROSARIO'],
            ['circuito_id' => 90, 'municipio' => 'ALVARADO'],
            ['circuito_id' => 6, 'municipio' => 'AMAGÁ'],
            ['circuito_id' => 7, 'municipio' => 'AMALFI'],
            ['circuito_id' => 105, 'municipio' => 'AMBALEMA'],
            ['circuito_id' => 100, 'municipio' => 'ANAPOIMA'],
            ['circuito_id' => 137, 'municipio' => 'ANCUYÁ'],
            ['circuito_id' => 207, 'municipio' => 'ANDALUCÍA'],
            ['circuito_id' => 8, 'municipio' => 'ANDES'],
            ['circuito_id' => 33, 'municipio' => 'ANGELÓPOLIS'],
            ['circuito_id' => 221, 'municipio' => 'ANGOSTURA'],
            ['circuito_id' => 70, 'municipio' => 'ANOLAIMA'],
            ['circuito_id' => 7, 'municipio' => 'ANORÍ'],
            ['circuito_id' => 9, 'municipio' => 'ANSERMA'],
            ['circuito_id' => 40, 'municipio' => 'ANSERMANUEVO'],
            ['circuito_id' => 10, 'municipio' => 'ANTIOQUIA'],
            ['circuito_id' => 180, 'municipio' => 'ANZÁ'],
            ['circuito_id' => 105, 'municipio' => 'ANZOÁTEGUI'],
            ['circuito_id' => 12, 'municipio' => 'APARTADÓ'],
            ['circuito_id' => 13, 'municipio' => 'APÍA'],
            ['circuito_id' => 100, 'municipio' => 'APULO'],
            ['circuito_id' => 199, 'municipio' => 'AQUITANIA'],
            ['circuito_id' => 75, 'municipio' => 'ARACATACA'],
            ['circuito_id' => 169, 'municipio' => 'ARANZAZÚ'],
            ['circuito_id' => 172, 'municipio' => 'ARATOCA'],
            ['circuito_id' => 14, 'municipio' => 'ARAUCA'],
            ['circuito_id' => 187, 'municipio' => 'ARAUQUITA'],
            ['circuito_id' => 77, 'municipio' => 'ARBELÁEZ'],
            ['circuito_id' => 103, 'municipio' => 'ARBOLEDA'],
            ['circuito_id' => 59, 'municipio' => 'ARBOLEDAS'],
            ['circuito_id' => 212, 'municipio' => 'ARBOLETES'],
            ['circuito_id' => 209, 'municipio' => 'ARCABUCO'],
            ['circuito_id' => 192, 'municipio' => 'ARENAL'],
            ['circuito_id' => 201, 'municipio' => 'ARGELIA'],
            ['circuito_id' => 146, 'municipio' => 'ARIGUANÍ'],
            ['circuito_id' => 211, 'municipio' => 'ARJONA'],
            ['circuito_id' => 93, 'municipio' => 'ARMENIA'],
            ['circuito_id' => 211, 'municipio' => 'ARROYOHONDO'],
            ['circuito_id' => 50, 'municipio' => 'ASTREA'],
            ['circuito_id' => 45, 'municipio' => 'ATACO'],
            ['circuito_id' => 158, 'municipio' => 'ATRATO'],
            ['circuito_id' => 17, 'municipio' => 'AYAPEL'],
            ['circuito_id' => 92, 'municipio' => 'BAGADÓ'],
            ['circuito_id' => 18, 'municipio' => 'BAHÍA SOLANO'],
            ['circuito_id' => 92, 'municipio' => 'BAJO BAUDÓ'],
            ['circuito_id' => 138, 'municipio' => 'BALBOA'],
            ['circuito_id' => 167, 'municipio' => 'BARANOA'],
            ['circuito_id' => 130, 'municipio' => 'BARAYA'],
            ['circuito_id' => 19, 'municipio' => 'BARBACOAS'],
            ['circuito_id' => 82, 'municipio' => 'BARBOSA'],
            ['circuito_id' => 172, 'municipio' => 'BARICHARA'],
            ['circuito_id' => 219, 'municipio' => 'BARRANCA DE UPÍA'],
            ['circuito_id' => 20, 'municipio' => 'BARRANCABERMEJA'],
            ['circuito_id' => 174, 'municipio' => 'BARRANCAS'],
            ['circuito_id' => 124, 'municipio' => 'BARRANCO DE LOBA'],
            ['circuito_id' => 16, 'municipio' => 'BARRANQUILLA'],
            ['circuito_id' => 216, 'municipio' => 'BECERRIL'],
            ['circuito_id' => 9, 'municipio' => 'BELALCAZAR'],
            ['circuito_id' => 184, 'municipio' => 'BELÉN'],
            ['circuito_id' => 164, 'municipio' => 'BELÉN DE BAJIRÁ'],
            ['circuito_id' => 22, 'municipio' => 'BELÉN DE LOS ANDAQUÍES'],
            ['circuito_id' => 23, 'municipio' => 'BELÉN DE UMBRÍA'],
            ['circuito_id' => 24, 'municipio' => 'BELLO'],
            ['circuito_id' => 177, 'municipio' => 'BELMIRA'],
            ['circuito_id' => 105, 'municipio' => 'BELTRÁN'],
            ['circuito_id' => 121, 'municipio' => 'BERBEO'],
            ['circuito_id' => 8, 'municipio' => 'BETANIA'],
            ['circuito_id' => 140, 'municipio' => 'BETEITIVA'],
            ['circuito_id' => 56, 'municipio' => 'BETULIA'],
            ['circuito_id' => 70, 'municipio' => 'BITUIMA'],
            ['circuito_id' => 196, 'municipio' => 'BOAVITA'],
            ['circuito_id' => 136, 'municipio' => 'BOCHALEMA'],
            ['circuito_id' => 25, 'municipio' => 'BOGOTÁ'],
            ['circuito_id' => 70, 'municipio' => 'BOJACÁ'],
            ['circuito_id' => 158, 'municipio' => 'BOJAYÁ'],
            ['circuito_id' => 27, 'municipio' => 'BOLÍVAR'],
            ['circuito_id' => 216, 'municipio' => 'BOSCONIA'],
            ['circuito_id' => 209, 'municipio' => 'BOYACÁ'],
            ['circuito_id' => 221, 'municipio' => 'BRICEÑO'],
            ['circuito_id' => 185, 'municipio' => 'BUCARAMANGA'],
            ['circuito_id' => 59, 'municipio' => 'BUCARASICA'],
            ['circuito_id' => 30, 'municipio' => 'BUENAVENTURA'],
            ['circuito_id' => 49, 'municipio' => 'BUENAVISTA'],
            ['circuito_id' => 186, 'municipio' => 'BUENOS AIRES'],
            ['circuito_id' => 137, 'municipio' => 'BUESACO'],
            ['circuito_id' => 31, 'municipio' => 'BUGA'],
            ['circuito_id' => 207, 'municipio' => 'BUGALAGRANDE'],
            ['circuito_id' => 180, 'municipio' => 'BURITICÁ'],
            ['circuito_id' => 184, 'municipio' => 'BUSBANZA'],
            ['circuito_id' => 77, 'municipio' => 'CABRERA'],
            ['circuito_id' => 153, 'municipio' => 'CABUYARO'],
            ['circuito_id' => 42, 'municipio' => 'CÁCERES'],
            ['circuito_id' => 70, 'municipio' => 'CACHIPAY'],
            ['circuito_id' => 29, 'municipio' => 'CÁCHIRA'],
            ['circuito_id' => 136, 'municipio' => 'CÁCOTA'],
            ['circuito_id' => 180, 'municipio' => 'CAICEDO'],
            ['circuito_id' => 189, 'municipio' => 'CAICEDONIA'],
            ['circuito_id' => 175, 'municipio' => 'CAIMITO'],
            ['circuito_id' => 90, 'municipio' => 'CAJAMARCA'],
            ['circuito_id' => 147, 'municipio' => 'CAJIBÍO'],
            ['circuito_id' => 224, 'municipio' => 'CAJICÁ'],
            ['circuito_id' => 211, 'municipio' => 'CALAMAR'],
            ['circuito_id' => 32, 'municipio' => 'CALARCÁ'],
            ['circuito_id' => 33, 'municipio' => 'CALDAS'],
            ['circuito_id' => 186, 'municipio' => 'CALDONO'],
            ['circuito_id' => 215, 'municipio' => 'CALI'],
            ['circuito_id' => 29, 'municipio' => 'CALIFORNIA'],
            ['circuito_id' => 31, 'municipio' => 'CALIMA'],
            ['circuito_id' => 35, 'municipio' => 'CALOTO'],
            ['circuito_id' => 221, 'municipio' => 'CAMPAMENTO'],
            ['circuito_id' => 167, 'municipio' => 'CAMPO DE LA CRUZ'],
            ['circuito_id' => 130, 'municipio' => 'CAMPOALEGRE'],
            ['circuito_id' => 121, 'municipio' => 'CAMPOHERMOSO'],
            ['circuito_id' => 127, 'municipio' => 'CANALETE'],
            ['circuito_id' => 167, 'municipio' => 'CANDELARIA'],
            ['circuito_id' => 192, 'municipio' => 'CANTAGALLO'],
            ['circuito_id' => 158, 'municipio' => 'CANTÓN DE SAN PABLO'],
            ['circuito_id' => 74, 'municipio' => 'CAÑASGORDAS'],
            ['circuito_id' => 101, 'municipio' => 'CAPARRAPÍ'],
            ['circuito_id' => 114, 'municipio' => 'CAPITANEJO'],
            ['circuito_id' => 37, 'municipio' => 'CÁQUEZA'],
            ['circuito_id' => 149, 'municipio' => 'CARACOLÍ'],
            ['circuito_id' => 204, 'municipio' => 'CARAMANTA'],
            ['circuito_id' => 114, 'municipio' => 'CARCASÍ'],
            ['circuito_id' => 12, 'municipio' => 'CAREPA'],
            ['circuito_id' => 119, 'municipio' => 'CARMEN DE APICALÁ'],
            ['circuito_id' => 38, 'municipio' => 'CARMEN DE BOLÍVAR'],
            ['circuito_id' => 213, 'municipio' => 'CARMEN DE CARUPA'],
            ['circuito_id' => 164, 'municipio' => 'CARMEN DEL DARIÉN'],
            ['circuito_id' => 55, 'municipio' => 'CAROLINA'],
            ['circuito_id' => 27, 'municipio' => 'CARTAGENA'],
            ['circuito_id' => 154, 'municipio' => 'CARTAGENA DEL CHAIRÁ'],
            ['circuito_id' => 40, 'municipio' => 'CARTAGO'],
            ['circuito_id' => 122, 'municipio' => 'CARURÚ'],
            ['circuito_id' => 73, 'municipio' => 'CASABIANCA'],
            ['circuito_id' => 2, 'municipio' => 'CASTILLA LA NUEVA'],
            ['circuito_id' => 42, 'municipio' => 'CAUCASIA'],
            ['circuito_id' => 29, 'municipio' => 'CEPITÁ'],
            ['circuito_id' => 43, 'municipio' => 'CERETÉ'],
            ['circuito_id' => 184, 'municipio' => 'CERINZA'],
            ['circuito_id' => 114, 'municipio' => 'CERRITO'],
            ['circuito_id' => 144, 'municipio' => 'CERRO DE SAN ANTONIO'],
            ['circuito_id' => 92, 'municipio' => 'CERTEGUI'],
            ['circuito_id' => 137, 'municipio' => 'CHACHAGÜÍ'],
            ['circuito_id' => 84, 'municipio' => 'CHAGUANÍ'],
            ['circuito_id' => 58, 'municipio' => 'CHALÁN'],
            ['circuito_id' => 223, 'municipio' => 'CHÁMEZA'],
            ['circuito_id' => 45, 'municipio' => 'CHAPARRAL'],
            ['circuito_id' => 46, 'municipio' => 'CHARALÁ'],
            ['circuito_id' => 29, 'municipio' => 'CHARTA'],
            ['circuito_id' => 224, 'municipio' => 'CHÍA'],
            ['circuito_id' => 12, 'municipio' => 'CHIGORODÓ'],
            ['circuito_id' => 48, 'municipio' => 'CHIMA'],
            ['circuito_id' => 50, 'municipio' => 'CHIMICHAGUA'],
            ['circuito_id' => 136, 'municipio' => 'CHINÁCOTA'],
            ['circuito_id' => 79, 'municipio' => 'CHINAVITA'],
            ['circuito_id' => 47, 'municipio' => 'CHINCHINÁ'],
            ['circuito_id' => 48, 'municipio' => 'CHINÚ'],
            ['circuito_id' => 37, 'municipio' => 'CHIPAQUE'],
            ['circuito_id' => 217, 'municipio' => 'CHIPATÁ'],
            ['circuito_id' => 49, 'municipio' => 'CHIQUINQUIRÁ'],
            ['circuito_id' => 209, 'municipio' => 'CHÍQUIZA'],
            ['circuito_id' => 50, 'municipio' => 'CHIRIGUANÁ'],
            ['circuito_id' => 66, 'municipio' => 'CHISCAS'],
            ['circuito_id' => 197, 'municipio' => 'CHITA'],
            ['circuito_id' => 136, 'municipio' => 'CHITAGÁ'],
            ['circuito_id' => 125, 'municipio' => 'CHITARAQUE'],
            ['circuito_id' => 209, 'municipio' => 'CHIVATÁ'],
            ['circuito_id' => 146, 'municipio' => 'CHIVOLO'],
            ['circuito_id' => 87, 'municipio' => 'CHIVOR'],
            ['circuito_id' => 37, 'municipio' => 'CHOACHÍ'],
            ['circuito_id' => 52, 'municipio' => 'CHOCONTÁ'],
            ['circuito_id' => 124, 'municipio' => 'CICUCO'],
            ['circuito_id' => 53, 'municipio' => 'CIÉNAGA'],
            ['circuito_id' => 43, 'municipio' => 'CIÉNAGA DE ORO'],
            ['circuito_id' => 161, 'municipio' => 'CIÉNEGA'],
            ['circuito_id' => 54, 'municipio' => 'CIMITARRA'],
            ['circuito_id' => 15, 'municipio' => 'CIRCASIA'],
            ['circuito_id' => 55, 'municipio' => 'CISNEROS'],
            ['circuito_id' => 39, 'municipio' => 'CLEMENCIA'],
            ['circuito_id' => 67, 'municipio' => 'COCORNÁ'],
            ['circuito_id' => 69, 'municipio' => 'COELLO'],
            ['circuito_id' => 224, 'municipio' => 'COGUA'],
            ['circuito_id' => 130, 'municipio' => 'COLOMBIA'],
            ['circuito_id' => 97, 'municipio' => 'COLÓN'],
            ['circuito_id' => 194, 'municipio' => 'COLOSÓ'],
            ['circuito_id' => 209, 'municipio' => 'CÓMBITA'],
            ['circuito_id' => 163, 'municipio' => 'CONCEPCIÓN'],
            ['circuito_id' => 56, 'municipio' => 'CONCORDIA'],
            ['circuito_id' => 92, 'municipio' => 'CONDOTO'],
            ['circuito_id' => 198, 'municipio' => 'CONFINES'],
            ['circuito_id' => 137, 'municipio' => 'CONSACÁ'],
            ['circuito_id' => 91, 'municipio' => 'CONTADERO'],
            ['circuito_id' => 198, 'municipio' => 'CONTRATACIÓN'],
            ['circuito_id' => 132, 'municipio' => 'CONVENCIÓN'],
            ['circuito_id' => 24, 'municipio' => 'COPACABANA'],
            ['circuito_id' => 49, 'municipio' => 'COPER'],
            ['circuito_id' => 38, 'municipio' => 'CÓRDOBA'],
            ['circuito_id' => 35, 'municipio' => 'CORINTO'],
            ['circuito_id' => 46, 'municipio' => 'COROMORO'],
            ['circuito_id' => 58, 'municipio' => 'COROZAL'],
            ['circuito_id' => 184, 'municipio' => 'CORRALES'],
            ['circuito_id' => 76, 'municipio' => 'COTA'],
            ['circuito_id' => 43, 'municipio' => 'COTORRA'],
            ['circuito_id' => 196, 'municipio' => 'COVARACHÍA'],
            ['circuito_id' => 194, 'municipio' => 'COVEÑAS'],
            ['circuito_id' => 85, 'municipio' => 'COYAIMA'],
            ['circuito_id' => 14, 'municipio' => 'CRAVO NORTE'],
            ['circuito_id' => 91, 'municipio' => 'CUASPUD'],
            ['circuito_id' => 187, 'municipio' => 'CUBARÁ'],
            ['circuito_id' => 2, 'municipio' => 'CUBARRAL'],
            ['circuito_id' => 209, 'municipio' => 'CUCAITA'],
            ['circuito_id' => 213, 'municipio' => 'CUCUNUBÁ'],
            ['circuito_id' => 131, 'municipio' => 'CÚCUTA'],
            ['circuito_id' => 136, 'municipio' => 'CUCUTILLA'],
            ['circuito_id' => 199, 'municipio' => 'CUÍTIVA'],
            ['circuito_id' => 219, 'municipio' => 'CUMARAL'],
            ['circuito_id' => 151, 'municipio' => 'CUMARIBO'],
            ['circuito_id' => 91, 'municipio' => 'CUMBAL'],
            ['circuito_id' => 170, 'municipio' => 'CUMBITARA'],
            ['circuito_id' => 119, 'municipio' => 'CUNDAY'],
            ['circuito_id' => 22, 'municipio' => 'CURILLO'],
            ['circuito_id' => 172, 'municipio' => 'CURITÍ'],
            ['circuito_id' => 50, 'municipio' => 'CURUMANÍ'],
            ['circuito_id' => 61, 'municipio' => 'DABEIBA'],
            ['circuito_id' => 34, 'municipio' => 'DAGUA'],
            ['circuito_id' => 162, 'municipio' => 'DIBULLA'],
            ['circuito_id' => 174, 'municipio' => 'DISTRACCIÓN'],
            ['circuito_id' => 157, 'municipio' => 'DOLORES'],
            ['circuito_id' => 183, 'municipio' => 'DON MATÍAS'],
            ['circuito_id' => 62, 'municipio' => 'DOSQUEBRADAS'],
            ['circuito_id' => 63, 'municipio' => 'DUITAMA'],
            ['circuito_id' => 109, 'municipio' => 'DURANIA'],
            ['circuito_id' => 180, 'municipio' => 'EBÉJICO'],
            ['circuito_id' => 40, 'municipio' => 'EL ÁGUILA'],
            ['circuito_id' => 64, 'municipio' => 'EL BAGRE'],
            ['circuito_id' => 65, 'municipio' => 'EL BANCO'],
            ['circuito_id' => 40, 'municipio' => 'EL CAIRO'],
            ['circuito_id' => 219, 'municipio' => 'EL CALVARIO'],
            ['circuito_id' => 132, 'municipio' => 'EL CARMEN'],
            ['circuito_id' => 158, 'municipio' => 'EL CARMEN DE ATRATO'],
            ['circuito_id' => 178, 'municipio' => 'EL CARMEN DE CHUCURÍ'],
            ['circuito_id' => 163, 'municipio' => 'EL CARMEN DE VIBORAL'],
            ['circuito_id' => 2, 'municipio' => 'EL CASTILLO'],
            ['circuito_id' => 135, 'municipio' => 'EL CERRITO'],
            ['circuito_id' => 208, 'municipio' => 'EL CHARCO'],
            ['circuito_id' => 66, 'municipio' => 'EL COCUY'],
            ['circuito_id' => 100, 'municipio' => 'EL COLEGIO'],
            ['circuito_id' => 216, 'municipio' => 'EL COPEY'],
            ['circuito_id' => 154, 'municipio' => 'EL DONCELLO'],
            ['circuito_id' => 2, 'municipio' => 'EL DORADO'],
            ['circuito_id' => 166, 'municipio' => 'EL DOVIO'],
            ['circuito_id' => 66, 'municipio' => 'EL ESPINO'],
            ['circuito_id' => 198, 'municipio' => 'EL GUACAMAYO'],
            ['circuito_id' => 38, 'municipio' => 'EL GUAMO'],
            ['circuito_id' => 218, 'municipio' => 'EL MOLINO'],
            ['circuito_id' => 50, 'municipio' => 'EL PASO'],
            ['circuito_id' => 154, 'municipio' => 'EL PAUJIL'],
            ['circuito_id' => 117, 'municipio' => 'EL PEÑOL'],
            ['circuito_id' => 124, 'municipio' => 'EL PEÑÓN'],
            ['circuito_id' => 144, 'municipio' => 'EL PIÑÓN'],
            ['circuito_id' => 29, 'municipio' => 'EL PLAYÓN'],
            ['circuito_id' => 75, 'municipio' => 'EL RETÉN'],
            ['circuito_id' => 96, 'municipio' => 'EL RETIRO'],
            ['circuito_id' => 173, 'municipio' => 'EL RETORNO'],
            ['circuito_id' => 194, 'municipio' => 'EL ROBLE'],
            ['circuito_id' => 76, 'municipio' => 'EL ROSAL'],
            ['circuito_id' => 137, 'municipio' => 'EL ROSARIO'],
            ['circuito_id' => 67, 'municipio' => 'EL SANTUARIO'],
            ['circuito_id' => 137, 'municipio' => 'EL TABLÓN DE GÓMEZ'],
            ['circuito_id' => 147, 'municipio' => 'EL TAMBO'],
            ['circuito_id' => 132, 'municipio' => 'EL TARRA'],
            ['circuito_id' => 59, 'municipio' => 'EL ZULIA'],
            ['circuito_id' => 143, 'municipio' => 'ELÍAS'],
            ['circuito_id' => 46, 'municipio' => 'ENCINO'],
            ['circuito_id' => 114, 'municipio' => 'ENCISO'],
            ['circuito_id' => 177, 'municipio' => 'ENTRERRÍOS'],
            ['circuito_id' => 68, 'municipio' => 'ENVIGADO'],
            ['circuito_id' => 69, 'municipio' => 'ESPINAL'],
            ['circuito_id' => 70, 'municipio' => 'FACATATIVÁ'],
            ['circuito_id' => 88, 'municipio' => 'FALAN'],
            ['circuito_id' => 115, 'municipio' => 'FILADELFIA'],
            ['circuito_id' => 15, 'municipio' => 'FILANDIA'],
            ['circuito_id' => 199, 'municipio' => 'FIRAVITOBA'],
            ['circuito_id' => 81, 'municipio' => 'FLANDES'],
            ['circuito_id' => 36, 'municipio' => 'FLORENCIA'],
            ['circuito_id' => 184, 'municipio' => 'FLORESTA'],
            ['circuito_id' => 148, 'municipio' => 'FLORIÁN'],
            ['circuito_id' => 135, 'municipio' => 'FLORIDA'],
            ['circuito_id' => 29, 'municipio' => 'FLORIDABLANCA'],
            ['circuito_id' => 37, 'municipio' => 'FÓMEQUE'],
            ['circuito_id' => 174, 'municipio' => 'FONSECA'],
            ['circuito_id' => 187, 'municipio' => 'FORTUL'],
            ['circuito_id' => 37, 'municipio' => 'FOSCA'],
            ['circuito_id' => 208, 'municipio' => 'FRANCISCO PIZARRO'],
            ['circuito_id' => 72, 'municipio' => 'FREDONIA'],
            ['circuito_id' => 73, 'municipio' => 'FRESNO'],
            ['circuito_id' => 74, 'municipio' => 'FRONTINO'],
            ['circuito_id' => 83, 'municipio' => 'FUENTE DE ORO'],
            ['circuito_id' => 75, 'municipio' => 'FUNDACIÓN'],
            ['circuito_id' => 91, 'municipio' => 'FUNES'],
            ['circuito_id' => 76, 'municipio' => 'FUNZA'],
            ['circuito_id' => 213, 'municipio' => 'FÚQUENE'],
            ['circuito_id' => 77, 'municipio' => 'FUSAGASUGÁ'],
            ['circuito_id' => 78, 'municipio' => 'GACHALÁ'],
            ['circuito_id' => 224, 'municipio' => 'GACHANCIPÁ'],
            ['circuito_id' => 209, 'municipio' => 'GACHANTIVÁ'],
            ['circuito_id' => 78, 'municipio' => 'GACHETÁ'],
            ['circuito_id' => 172, 'municipio' => 'GALÁN'],
            ['circuito_id' => 21, 'municipio' => 'GALAPA'],
            ['circuito_id' => 193, 'municipio' => 'GALERAS'],
            ['circuito_id' => 78, 'municipio' => 'GAMA'],
            ['circuito_id' => 3, 'municipio' => 'GAMARRA'],
            ['circuito_id' => 198, 'municipio' => 'GÁMBITA'],
            ['circuito_id' => 199, 'municipio' => 'GÁMEZA'],
            ['circuito_id' => 79, 'municipio' => 'GARAGOA'],
            ['circuito_id' => 80, 'municipio' => 'GARZÓN'],
            ['circuito_id' => 32, 'municipio' => 'GÉNOVA'],
            ['circuito_id' => 80, 'municipio' => 'GIGANTE'],
            ['circuito_id' => 31, 'municipio' => 'GINEBRA'],
            ['circuito_id' => 180, 'municipio' => 'GIRALDO'],
            ['circuito_id' => 81, 'municipio' => 'GIRARDOT'],
            ['circuito_id' => 82, 'municipio' => 'GIRARDOTA'],
            ['circuito_id' => 29, 'municipio' => 'GIRÓN'],
            ['circuito_id' => 55, 'municipio' => 'GÓMEZ PLATA'],
            ['circuito_id' => 132, 'municipio' => 'GONZÁLEZ'],
            ['circuito_id' => 59, 'municipio' => 'GRAMALOTE'],
            ['circuito_id' => 67, 'municipio' => 'GRANADA'],
            ['circuito_id' => 114, 'municipio' => 'GUACA'],
            ['circuito_id' => 66, 'municipio' => 'GUACAMAYAS'],
            ['circuito_id' => 31, 'municipio' => 'GUACARÍ'],
            ['circuito_id' => 35, 'municipio' => 'GUACHENÉ'],
            ['circuito_id' => 213, 'municipio' => 'GUACHETÁ'],
            ['circuito_id' => 91, 'municipio' => 'GUACHUCAL'],
            ['circuito_id' => 55, 'municipio' => 'GUADALUPE'],
            ['circuito_id' => 84, 'municipio' => 'GUADUAS'],
            ['circuito_id' => 210, 'municipio' => 'GUAITARILLA'],
            ['circuito_id' => 91, 'municipio' => 'GUALMATÁN'],
            ['circuito_id' => 65, 'municipio' => 'GUAMAL'],
            ['circuito_id' => 85, 'municipio' => 'GUAMO'],
            ['circuito_id' => 86, 'municipio' => 'GUAPÍ'],
            ['circuito_id' => 198, 'municipio' => 'GUAPOTÁ'],
            ['circuito_id' => 113, 'municipio' => 'GUARANDÁ'],
            ['circuito_id' => 163, 'municipio' => 'GUARNE'],
            ['circuito_id' => 52, 'municipio' => 'GUASCA'],
            ['circuito_id' => 117, 'municipio' => 'GUATAPÉ'],
            ['circuito_id' => 81, 'municipio' => 'GUATAQUÍ'],
            ['circuito_id' => 52, 'municipio' => 'GUATAVITA'],
            ['circuito_id' => 87, 'municipio' => 'GUATEQUE'],
            ['circuito_id' => 159, 'municipio' => 'GUÁTICA'],
            ['circuito_id' => 217, 'municipio' => 'GUAVATÁ'],
            ['circuito_id' => 105, 'municipio' => 'GUAYABAL (ARMERO)'],
            ['circuito_id' => 70, 'municipio' => 'GUAYABAL DE SÍQUIMA'],
            ['circuito_id' => 219, 'municipio' => 'GUAYABETAL'],
            ['circuito_id' => 87, 'municipio' => 'GUAYATÁ'],
            ['circuito_id' => 217, 'municipio' => 'GÜEPSA'],
            ['circuito_id' => 66, 'municipio' => 'GÜICÁN'],
            ['circuito_id' => 37, 'municipio' => 'GUTIÉRREZ'],
            ['circuito_id' => 132, 'municipio' => 'HACARÍ'],
            ['circuito_id' => 124, 'municipio' => 'HATILLO DE LOBA'],
            ['circuito_id' => 198, 'municipio' => 'HATO'],
            ['circuito_id' => 139, 'municipio' => 'HATO COROZAL'],
            ['circuito_id' => 174, 'municipio' => 'HATO NUEVO'],
            ['circuito_id' => 93, 'municipio' => 'HELICONIA'],
            ['circuito_id' => 136, 'municipio' => 'HERRÁN'],
            ['circuito_id' => 73, 'municipio' => 'HERVEO'],
            ['circuito_id' => 8, 'municipio' => 'HISPANIA'],
            ['circuito_id' => 130, 'municipio' => 'HOBO'],
            ['circuito_id' => 88, 'municipio' => 'HONDA'],
            ['circuito_id' => 206, 'municipio' => 'IBAGUÉ'],
            ['circuito_id' => 119, 'municipio' => 'ICONONZO'],
            ['circuito_id' => 91, 'municipio' => 'ILES'],
            ['circuito_id' => 210, 'municipio' => 'IMUES'],
            ['circuito_id' => 152, 'municipio' => 'INÍRIDA'],
            ['circuito_id' => 191, 'municipio' => 'INZÁ'],
            ['circuito_id' => 91, 'municipio' => 'IPIALES'],
            ['circuito_id' => 130, 'municipio' => 'IQUIRA'],
            ['circuito_id' => 143, 'municipio' => 'ISNOS'],
            ['circuito_id' => 92, 'municipio' => 'ISTMINA'],
            ['circuito_id' => 93, 'municipio' => 'ITAGÜÍ'],
            ['circuito_id' => 94, 'municipio' => 'ITUANGO'],
            ['circuito_id' => 199, 'municipio' => 'IZA'],
            ['circuito_id' => 191, 'municipio' => 'JAMBALÓ'],
            ['circuito_id' => 34, 'municipio' => 'JAMUNDÍ'],
            ['circuito_id' => 8, 'municipio' => 'JARDÍN'],
            ['circuito_id' => 161, 'municipio' => 'JENESANO'],
            ['circuito_id' => 95, 'municipio' => 'JERICÓ'],
            ['circuito_id' => 81, 'municipio' => 'JERUSALÉN'],
            ['circuito_id' => 148, 'municipio' => 'JESÚS MARÍA'],
            ['circuito_id' => 172, 'municipio' => 'JORDÁN SUBE'],
            ['circuito_id' => 21, 'municipio' => 'JUAN DE ACOSTA'],
            ['circuito_id' => 78, 'municipio' => 'JUNÍN'],
            ['circuito_id' => 18, 'municipio' => 'JURADÓ'],
            ['circuito_id' => 126, 'municipio' => 'LA APARTADA'],
            ['circuito_id' => 102, 'municipio' => 'LA ARGENTINA'],
            ['circuito_id' => 148, 'municipio' => 'LA BELLEZA'],
            ['circuito_id' => 25, 'municipio' => 'LA CALERA'],
            ['circuito_id' => 87, 'municipio' => 'LA CAPILLA'],
            ['circuito_id' => 96, 'municipio' => 'LA CEJA'],
            ['circuito_id' => 104, 'municipio' => 'LA CELIA'],
            ['circuito_id' => 97, 'municipio' => 'LA CRUZ'],
            ['circuito_id' => 34, 'municipio' => 'LA CUMBRE'],
            ['circuito_id' => 98, 'municipio' => 'LA DORADA'],
            ['circuito_id' => 29, 'municipio' => 'LA ESPERANZA'],
            ['circuito_id' => 93, 'municipio' => 'LA ESTRELLA'],
            ['circuito_id' => 137, 'municipio' => 'LA FLORIDA'],
            ['circuito_id' => 3, 'municipio' => 'LA GLORIA'],
            ['circuito_id' => 50, 'municipio' => 'LA JAGUA DE IBIRICO'],
            ['circuito_id' => 218, 'municipio' => 'LA JAGUA DEL PILAR'],
            ['circuito_id' => 170, 'municipio' => 'LA LLANADA'],
            ['circuito_id' => 219, 'municipio' => 'LA MACARENA'],
            ['circuito_id' => 169, 'municipio' => 'LA MERCED'],
            ['circuito_id' => 100, 'municipio' => 'LA MESA'],
            ['circuito_id' => 71, 'municipio' => 'LA MONTAÑITA'],
            ['circuito_id' => 101, 'municipio' => 'LA PALMA'],
            ['circuito_id' => 217, 'municipio' => 'LA PAZ'],
            ['circuito_id' => 216, 'municipio' => 'LA PAZ (ROBLES)'],
            ['circuito_id' => 220, 'municipio' => 'LA PEÑA'],
            ['circuito_id' => 179, 'municipio' => 'LA PINTADA'],
            ['circuito_id' => 102, 'municipio' => 'LA PLATA'],
            ['circuito_id' => 132, 'municipio' => 'LA PLAYA'],
            ['circuito_id' => 151, 'municipio' => 'LA PRIMAVERA'],
            ['circuito_id' => 139, 'municipio' => 'LA SALINA'],
            ['circuito_id' => 147, 'municipio' => 'LA SIERRA'],
            ['circuito_id' => 15, 'municipio' => 'LA TEBAIDA'],
            ['circuito_id' => 208, 'municipio' => 'LA TOLA'],
            ['circuito_id' => 96, 'municipio' => 'LA UNIÓN'],
            ['circuito_id' => 83, 'municipio' => 'LA URIBE'],
            ['circuito_id' => 196, 'municipio' => 'LA UVITA'],
            ['circuito_id' => 27, 'municipio' => 'LA VEGA'],
            ['circuito_id' => 49, 'municipio' => 'LA VICTORIA'],
            ['circuito_id' => 104, 'municipio' => 'LA VIRGINIA'],
            ['circuito_id' => 136, 'municipio' => 'LABATECA'],
            ['circuito_id' => 199, 'municipio' => 'LABRANZAGRANDE'],
            ['circuito_id' => 54, 'municipio' => 'LANDÁZURI'],
            ['circuito_id' => 29, 'municipio' => 'LEBRIJA'],
            ['circuito_id' => 83, 'municipio' => 'LEJANÍAS'],
            ['circuito_id' => 213, 'municipio' => 'LENGUAZAQUE'],
            ['circuito_id' => 105, 'municipio' => 'LÉRIDA'],
            ['circuito_id' => 106, 'municipio' => 'LETICIA'],
            ['circuito_id' => 137, 'municipio' => 'LEYVA'],
            ['circuito_id' => 107, 'municipio' => 'LÍBANO'],
            ['circuito_id' => 202, 'municipio' => 'LIBORINA'],
            ['circuito_id' => 170, 'municipio' => 'LINARES'],
            ['circuito_id' => 92, 'municipio' => 'LITORAL DE SAN JUAN'],
            ['circuito_id' => 158, 'municipio' => 'LLORÓ'],
            ['circuito_id' => 86, 'municipio' => 'LÓPEZ DE MICAY'],
            ['circuito_id' => 108, 'municipio' => 'LORICA'],
            ['circuito_id' => 170, 'municipio' => 'LOS ANDES'],
            ['circuito_id' => 127, 'municipio' => 'LOS CÓRDOBAS'],
            ['circuito_id' => 58, 'municipio' => 'LOS PALMITOS'],
            ['circuito_id' => 109, 'municipio' => 'LOS PATIOS'],
            ['circuito_id' => 29, 'municipio' => 'LOS SANTOS'],
            ['circuito_id' => 59, 'municipio' => 'LOURDES'],
            ['circuito_id' => 167, 'municipio' => 'LURUACO'],
            ['circuito_id' => 79, 'municipio' => 'MACANAL'],
            ['circuito_id' => 114, 'municipio' => 'MACARAVITA'],
            ['circuito_id' => 149, 'municipio' => 'MACEO'],
            ['circuito_id' => 52, 'municipio' => 'MACHETÁ'],
            ['circuito_id' => 76, 'municipio' => 'MADRID'],
            ['circuito_id' => 110, 'municipio' => 'MAGANGUÉ'],
            ['circuito_id' => 19, 'municipio' => 'MAGÜI-PAYÁN'],
            ['circuito_id' => 211, 'municipio' => 'MAHATES'],
            ['circuito_id' => 112, 'municipio' => 'MAICAO'],
            ['circuito_id' => 113, 'municipio' => 'MAJAGUAL'],
            ['circuito_id' => 114, 'municipio' => 'MÁLAGA'],
            ['circuito_id' => 200, 'municipio' => 'MALAMBO'],
            ['circuito_id' => 210, 'municipio' => 'MALLAMA'],
            ['circuito_id' => 167, 'municipio' => 'MANATÍ'],
            ['circuito_id' => 216, 'municipio' => 'MANAURE'],
            ['circuito_id' => 223, 'municipio' => 'MANÍ'],
            ['circuito_id' => 33, 'municipio' => 'MANIZALES'],
            ['circuito_id' => 52, 'municipio' => 'MANTA'],
            ['circuito_id' => 116, 'municipio' => 'MANZANARES'],
            ['circuito_id' => 219, 'municipio' => 'MAPIRIPÁN'],
            ['circuito_id' => 124, 'municipio' => 'MARGARITA'],
            ['circuito_id' => 211, 'municipio' => 'MARÍA LA BAJA'],
            ['circuito_id' => 117, 'municipio' => 'MARINILLA'],
            ['circuito_id' => 49, 'municipio' => 'MARIPÍ'],
            ['circuito_id' => 88, 'municipio' => 'MARIQUITA'],
            ['circuito_id' => 164, 'municipio' => 'MARMATO'],
            ['circuito_id' => 116, 'municipio' => 'MARQUETALIA'],
            ['circuito_id' => 142, 'municipio' => 'MARSELLA'],
            ['circuito_id' => 169, 'municipio' => 'MARULANDA'],
            ['circuito_id' => 29, 'municipio' => 'MATANZA'],
            ['circuito_id' => 10, 'municipio' => 'MEDELLÍN'],
            ['circuito_id' => 219, 'municipio' => 'MEDINA'],
            ['circuito_id' => 158, 'municipio' => 'MEDIO ATRATO'],
            ['circuito_id' => 92, 'municipio' => 'MEDIO BAUDÓ'],
            ['circuito_id' => 92, 'municipio' => 'MEDIO SAN JUAN'],
            ['circuito_id' => 119, 'municipio' => 'MELGAR'],
            ['circuito_id' => 138, 'municipio' => 'MERCADERES'],
            ['circuito_id' => 83, 'municipio' => 'MESETAS'],
            ['circuito_id' => 71, 'municipio' => 'MILÁN'],
            ['circuito_id' => 121, 'municipio' => 'MIRAFLORES'],
            ['circuito_id' => 155, 'municipio' => 'MIRANDA'],
            ['circuito_id' => 23, 'municipio' => 'MISTRATÓ'],
            ['circuito_id' => 122, 'municipio' => 'MITÚ'],
            ['circuito_id' => 123, 'municipio' => 'MOCOA'],
            ['circuito_id' => 172, 'municipio' => 'MOGOTES'],
            ['circuito_id' => 114, 'municipio' => 'MOLAGAVITA'],
            ['circuito_id' => 108, 'municipio' => 'MOMIL'],
            ['circuito_id' => 124, 'municipio' => 'MOMPÓS'],
            ['circuito_id' => 199, 'municipio' => 'MONGUA'],
            ['circuito_id' => 199, 'municipio' => 'MONGUÍ'],
            ['circuito_id' => 125, 'municipio' => 'MONIQUIRÁ'],
            ['circuito_id' => 179, 'municipio' => 'MONTEBELLO'],
            ['circuito_id' => 110, 'municipio' => 'MONTECRISTO'],
            ['circuito_id' => 126, 'municipio' => 'MONTELÍBANO'],
            ['circuito_id' => 15, 'municipio' => 'MONTENEGRO'],
            ['circuito_id' => 57, 'municipio' => 'MONTERÍA'],
            ['circuito_id' => 128, 'municipio' => 'MONTERREY'],
            ['circuito_id' => 108, 'municipio' => 'MOÑITOS'],
            ['circuito_id' => 192, 'municipio' => 'MORALES'],
            ['circuito_id' => 22, 'municipio' => 'MORELIA'],
            ['circuito_id' => 58, 'municipio' => 'MORROA'],
            ['circuito_id' => 76, 'municipio' => 'MOSQUERA'],
            ['circuito_id' => 209, 'municipio' => 'MOTAVITA'],
            ['circuito_id' => 107, 'municipio' => 'MURILLO'],
            ['circuito_id' => 12, 'municipio' => 'MURINDÓ'],
            ['circuito_id' => 12, 'municipio' => 'MUTATÁ'],
            ['circuito_id' => 136, 'municipio' => 'MUTISCUA'],
            ['circuito_id' => 49, 'municipio' => 'MUZO'],
            ['circuito_id' => 201, 'municipio' => 'NARIÑO'],
            ['circuito_id' => 102, 'municipio' => 'NÁTAGA'],
            ['circuito_id' => 85, 'municipio' => 'NATAGAIMA'],
            ['circuito_id' => 42, 'municipio' => 'NECHÍ'],
            ['circuito_id' => 212, 'municipio' => 'NECOCLÍ'],
            ['circuito_id' => 115, 'municipio' => 'NEIRA'],
            ['circuito_id' => 89, 'municipio' => 'NEIVA'],
            ['circuito_id' => 224, 'municipio' => 'NEMOCÓN'],
            ['circuito_id' => 81, 'municipio' => 'NILO'],
            ['circuito_id' => 220, 'municipio' => 'NIMAIMA'],
            ['circuito_id' => 63, 'municipio' => 'NOBSA'],
            ['circuito_id' => 220, 'municipio' => 'NOCAIMA'],
            ['circuito_id' => 98, 'municipio' => 'NORCASIA'],
            ['circuito_id' => 192, 'municipio' => 'NOROSÍ'],
            ['circuito_id' => 92, 'municipio' => 'NÓVITA'],
            ['circuito_id' => 146, 'municipio' => 'NUEVA GRANADA'],
            ['circuito_id' => 161, 'municipio' => 'NUEVO COLÓN'],
            ['circuito_id' => 223, 'municipio' => 'NUNCHÍA'],
            ['circuito_id' => 158, 'municipio' => 'NUQUÍ'],
            ['circuito_id' => 40, 'municipio' => 'OBANDO'],
            ['circuito_id' => 46, 'municipio' => 'OCAMONTE'],
            ['circuito_id' => 132, 'municipio' => 'OCAÑA'],
            ['circuito_id' => 198, 'municipio' => 'OIBA'],
            ['circuito_id' => 209, 'municipio' => 'OICATÁ'],
            ['circuito_id' => 202, 'municipio' => 'OLAYA'],
            ['circuito_id' => 208, 'municipio' => 'OLAYA HERRERA'],
            ['circuito_id' => 172, 'municipio' => 'ONZAGA'],
            ['circuito_id' => 143, 'municipio' => 'OPORAPA'],
            ['circuito_id' => 156, 'municipio' => 'ORITO'],
            ['circuito_id' => 133, 'municipio' => 'OROCUÉ'],
            ['circuito_id' => 85, 'municipio' => 'ORTEGA'],
            ['circuito_id' => 210, 'municipio' => 'OSPINA'],
            ['circuito_id' => 49, 'municipio' => 'OTANCHE'],
            ['circuito_id' => 58, 'municipio' => 'OVEJAS'],
            ['circuito_id' => 79, 'municipio' => 'PACHAVITA'],
            ['circuito_id' => 134, 'municipio' => 'PACHO'],
            ['circuito_id' => 4, 'municipio' => 'PÁCORA'],
            ['circuito_id' => 155, 'municipio' => 'PADILLA'],
            ['circuito_id' => 121, 'municipio' => 'PÁEZ'],
            ['circuito_id' => 191, 'municipio' => 'PAEZ - BELALCÁZAR'],
            ['circuito_id' => 102, 'municipio' => 'PAICOL'],
            ['circuito_id' => 50, 'municipio' => 'PAILITAS'],
            ['circuito_id' => 134, 'municipio' => 'PAIME'],
            ['circuito_id' => 63, 'municipio' => 'PAIPA'],
            ['circuito_id' => 223, 'municipio' => 'PAJARITO'],
            ['circuito_id' => 130, 'municipio' => 'PALERMO'],
            ['circuito_id' => 47, 'municipio' => 'PALESTINA'],
            ['circuito_id' => 198, 'municipio' => 'PALMAR'],
            ['circuito_id' => 200, 'municipio' => 'PALMAR DE VARELA'],
            ['circuito_id' => 198, 'municipio' => 'PALMAS DEL SOCORRO'],
            ['circuito_id' => 135, 'municipio' => 'PALMIRA'],
            ['circuito_id' => 194, 'municipio' => 'PALMITO'],
            ['circuito_id' => 88, 'municipio' => 'PALOCABILDO'],
            ['circuito_id' => 136, 'municipio' => 'PAMPLONA'],
            ['circuito_id' => 136, 'municipio' => 'PAMPLONITA'],
            ['circuito_id' => 77, 'municipio' => 'PANDI'],
            ['circuito_id' => 66, 'municipio' => 'PANQUEBA'],
            ['circuito_id' => 172, 'municipio' => 'PÁRAMO'],
            ['circuito_id' => 219, 'municipio' => 'PARATEBUENO'],
            ['circuito_id' => 77, 'municipio' => 'PASCA'],
            ['circuito_id' => 129, 'municipio' => 'PASTO'],
            ['circuito_id' => 138, 'municipio' => 'PATÍA-EL BORDO'],
            ['circuito_id' => 49, 'municipio' => 'PAUNA'],
            ['circuito_id' => 199, 'municipio' => 'PAYA'],
            ['circuito_id' => 139, 'municipio' => 'PAZ DE ARIPORO'],
            ['circuito_id' => 140, 'municipio' => 'PAZ DE RÍO'],
            ['circuito_id' => 146, 'municipio' => 'PEDRAZA'],
            ['circuito_id' => 3, 'municipio' => 'PELAYA'],
            ['circuito_id' => 141, 'municipio' => 'PENSILVANIA'],
            ['circuito_id' => 61, 'municipio' => 'PEQUÉ'],
            ['circuito_id' => 165, 'municipio' => 'PEREIRA'],
            ['circuito_id' => 199, 'municipio' => 'PESCA'],
            ['circuito_id' => 123, 'municipio' => 'PIAMONTE'],
            ['circuito_id' => 29, 'municipio' => 'PIEDECUESTA'],
            ['circuito_id' => 90, 'municipio' => 'PIEDRAS'],
            ['circuito_id' => 147, 'municipio' => 'PIENDAMÓ'],
            ['circuito_id' => 32, 'municipio' => 'PIJAO'],
            ['circuito_id' => 65, 'municipio' => 'PIJIÑO DEL CARMEN'],
            ['circuito_id' => 172, 'municipio' => 'PINCHOTE'],
            ['circuito_id' => 110, 'municipio' => 'PINILLOS'],
            ['circuito_id' => 21, 'municipio' => 'PIOJÓ'],
            ['circuito_id' => 199, 'municipio' => 'PISBA'],
            ['circuito_id' => 80, 'municipio' => 'PITAL'],
            ['circuito_id' => 143, 'municipio' => 'PITALITO'],
            ['circuito_id' => 144, 'municipio' => 'PIVIJAY'],
            ['circuito_id' => 45, 'municipio' => 'PLANADAS'],
            ['circuito_id' => 145, 'municipio' => 'PLANETA RICA'],
            ['circuito_id' => 146, 'municipio' => 'PLATO'],
            ['circuito_id' => 137, 'municipio' => 'POLICARPA'],
            ['circuito_id' => 167, 'municipio' => 'POLO NUEVO'],
            ['circuito_id' => 200, 'municipio' => 'PONEDERA'],
            ['circuito_id' => 41, 'municipio' => 'POPAYÁN'],
            ['circuito_id' => 139, 'municipio' => 'PORE'],
            ['circuito_id' => 91, 'municipio' => 'POTOSÍ'],
            ['circuito_id' => 135, 'municipio' => 'PRADERA'],
            ['circuito_id' => 157, 'municipio' => 'PRADO'],
            ['circuito_id' => 170, 'municipio' => 'PROVIDENCIA'],
            ['circuito_id' => 216, 'municipio' => 'PUEBLO BELLO'],
            ['circuito_id' => 145, 'municipio' => 'PUEBLO NUEVO'],
            ['circuito_id' => 95, 'municipio' => 'PUEBLO RICO'],
            ['circuito_id' => 53, 'municipio' => 'PUEBLO VIEJO'],
            ['circuito_id' => 148, 'municipio' => 'PUENTE NACIONAL'],
            ['circuito_id' => 91, 'municipio' => 'PUERRES'],
            ['circuito_id' => 156, 'municipio' => 'PUERTO ASÍS'],
            ['circuito_id' => 149, 'municipio' => 'PUERTO BERRÍO'],
            ['circuito_id' => 150, 'municipio' => 'PUERTO BOYACÁ'],
            ['circuito_id' => 156, 'municipio' => 'PUERTO CAICEDO'],
            ['circuito_id' => 151, 'municipio' => 'PUERTO CARREÑO'],
            ['circuito_id' => 21, 'municipio' => 'PUERTO COLOMBIA'],
            ['circuito_id' => 173, 'municipio' => 'PUERTO CONCORDIA'],
            ['circuito_id' => 127, 'municipio' => 'PUERTO ESCONDIDO'],
            ['circuito_id' => 153, 'municipio' => 'PUERTO GAITÁN'],
            ['circuito_id' => 123, 'municipio' => 'PUERTO GUZMÁN'],
            ['circuito_id' => 156, 'municipio' => 'PUERTO LEGUÍZAMO'],
            ['circuito_id' => 126, 'municipio' => 'PUERTO LIBERTADOR'],
            ['circuito_id' => 83, 'municipio' => 'PUERTO LLERAS'],
            ['circuito_id' => 153, 'municipio' => 'PUERTO LÓPEZ'],
            ['circuito_id' => 149, 'municipio' => 'PUERTO NARE'],
            ['circuito_id' => 106, 'municipio' => 'PUERTO NARIÑO'],
            ['circuito_id' => 20, 'municipio' => 'PUERTO PARRA'],
            ['circuito_id' => 154, 'municipio' => 'PUERTO RICO'],
            ['circuito_id' => 14, 'municipio' => 'PUERTO RONDÓN'],
            ['circuito_id' => 98, 'municipio' => 'PUERTO SALGAR'],
            ['circuito_id' => 59, 'municipio' => 'PUERTO SANTANDER'],
            ['circuito_id' => 155, 'municipio' => 'PUERTO TEJADA'],
            ['circuito_id' => 67, 'municipio' => 'PUERTO TRIUNFO'],
            ['circuito_id' => 20, 'municipio' => 'PUERTO WILCHES'],
            ['circuito_id' => 70, 'municipio' => 'PULÍ'],
            ['circuito_id' => 91, 'municipio' => 'PUPIALES'],
            ['circuito_id' => 147, 'municipio' => 'PURACÉ-COCONUCO'],
            ['circuito_id' => 157, 'municipio' => 'PURIFICACIÓN'],
            ['circuito_id' => 108, 'municipio' => 'PURÍSIMA'],
            ['circuito_id' => 220, 'municipio' => 'QUEBRADANEGRA'],
            ['circuito_id' => 37, 'municipio' => 'QUETAME'],
            ['circuito_id' => 51, 'municipio' => 'QUIBDÓ'],
            ['circuito_id' => 15, 'municipio' => 'QUIMBAYA'],
            ['circuito_id' => 159, 'municipio' => 'QUINCHÍA'],
            ['circuito_id' => 49, 'municipio' => 'QUÍPAMA'],
            ['circuito_id' => 70, 'municipio' => 'QUIPILE'],
            ['circuito_id' => 136, 'municipio' => 'RAGONVALIA'],
            ['circuito_id' => 161, 'municipio' => 'RAMIRIQUÍ'],
            ['circuito_id' => 49, 'municipio' => 'RÁQUIRA'],
            ['circuito_id' => 223, 'municipio' => 'RECETOR'],
            ['circuito_id' => 192, 'municipio' => 'REGIDOR'],
            ['circuito_id' => 188, 'municipio' => 'REMEDIOS'],
            ['circuito_id' => 53, 'municipio' => 'REMOLINO'],
            ['circuito_id' => 167, 'municipio' => 'REPELÓN'],
            ['circuito_id' => 219, 'municipio' => 'RESTREPO'],
            ['circuito_id' => 81, 'municipio' => 'RICAURTE'],
            ['circuito_id' => 132, 'municipio' => 'RÍO DE ORO'],
            ['circuito_id' => 92, 'municipio' => 'RÍO IRÓ'],
            ['circuito_id' => 158, 'municipio' => 'RÍO QUITO'],
            ['circuito_id' => 45, 'municipio' => 'RIOBLANCO'],
            ['circuito_id' => 207, 'municipio' => 'RIOFRÍO'],
            ['circuito_id' => 99, 'municipio' => 'RIOHACHA'],
            ['circuito_id' => 163, 'municipio' => 'RIONEGRO'],
            ['circuito_id' => 164, 'municipio' => 'RIOSUCIO'],
            ['circuito_id' => 192, 'municipio' => 'RIOVIEJO'],
            ['circuito_id' => 9, 'municipio' => 'RISARALDA'],
            ['circuito_id' => 130, 'municipio' => 'RIVERA'],
            ['circuito_id' => 19, 'municipio' => 'ROBERTO PAYÁN'],
            ['circuito_id' => 166, 'municipio' => 'ROLDANILLO'],
            ['circuito_id' => 90, 'municipio' => 'RONCESVALLES'],
            ['circuito_id' => 161, 'municipio' => 'RONDÓN'],
            ['circuito_id' => 147, 'municipio' => 'ROSAS'],
            ['circuito_id' => 90, 'municipio' => 'ROVIRA'],
            ['circuito_id' => 20, 'municipio' => 'SABANA DE TORRES'],
            ['circuito_id' => 200, 'municipio' => 'SABANAGRANDE'],
            ['circuito_id' => 202, 'municipio' => 'SABANALARGA'],
            ['circuito_id' => 146, 'municipio' => 'SABANAS DE SAN ÁNGEL'],
            ['circuito_id' => 68, 'municipio' => 'SABANETA'],
            ['circuito_id' => 49, 'municipio' => 'SABOYÁ'],
            ['circuito_id' => 139, 'municipio' => 'SÁCAMA'],
            ['circuito_id' => 209, 'municipio' => 'SÁCHICA'],
            ['circuito_id' => 168, 'municipio' => 'SAHAGÚN'],
            ['circuito_id' => 143, 'municipio' => 'SALADOBLANCO'],
            ['circuito_id' => 169, 'municipio' => 'SALAMINA'],
            ['circuito_id' => 59, 'municipio' => 'SALAZAR'],
            ['circuito_id' => 85, 'municipio' => 'SALDAÑA'],
            ['circuito_id' => 15, 'municipio' => 'SALENTO'],
            ['circuito_id' => 27, 'municipio' => 'SALGAR'],
            ['circuito_id' => 209, 'municipio' => 'SAMACÁ'],
            ['circuito_id' => 98, 'municipio' => 'SAMANÁ'],
            ['circuito_id' => 170, 'municipio' => 'SAMANIEGO'],
            ['circuito_id' => 194, 'municipio' => 'SAMPUÉS'],
            ['circuito_id' => 143, 'municipio' => 'SAN AGUSTÍN'],
            ['circuito_id' => 3, 'municipio' => 'SAN ALBERTO'],
            ['circuito_id' => 171, 'municipio' => 'SAN ANDRÉS'],
            ['circuito_id' => 48, 'municipio' => 'SAN ANDRÉS  DE SOTAVENTO'],
            ['circuito_id' => 114, 'municipio' => 'SAN ANDRÉS DE BUGA'],
            ['circuito_id' => 94, 'municipio' => 'SAN ANDRÉS DE CUERQUÍA'],
            ['circuito_id' => 108, 'municipio' => 'SAN ANTERO'],
            ['circuito_id' => 45, 'municipio' => 'SAN ANTONIO'],
            ['circuito_id' => 100, 'municipio' => 'SAN ANTONIO DEL TEQUENDAMA'],
            ['circuito_id' => 217, 'municipio' => 'SAN BENITO'],
            ['circuito_id' => 193, 'municipio' => 'SAN BENITO ABAD'],
            ['circuito_id' => 77, 'municipio' => 'SAN BERNARDO'],
            ['circuito_id' => 108, 'municipio' => 'SAN BERNARDO DEL VIENTO'],
            ['circuito_id' => 132, 'municipio' => 'SAN CALIXTO'],
            ['circuito_id' => 117, 'municipio' => 'SAN CARLOS'],
            ['circuito_id' => 2, 'municipio' => 'SAN CARLOS DE GUAROA'],
            ['circuito_id' => 224, 'municipio' => 'SAN CAYETANO'],
            ['circuito_id' => 39, 'municipio' => 'SAN CRISTOBAL'],
            ['circuito_id' => 216, 'municipio' => 'SAN DIEGO'],
            ['circuito_id' => 121, 'municipio' => 'SAN EDUARDO'],
            ['circuito_id' => 39, 'municipio' => 'SAN ESTANISLAO'],
            ['circuito_id' => 124, 'municipio' => 'SAN FERNANDO'],
            ['circuito_id' => 67, 'municipio' => 'SAN FRANCISCO'],
            ['circuito_id' => 172, 'municipio' => 'SAN GIL'],
            ['circuito_id' => 38, 'municipio' => 'SAN JACINTO'],
            ['circuito_id' => 110, 'municipio' => 'SAN JACINTO DEL CAUCA'],
            ['circuito_id' => 180, 'municipio' => 'SAN JERÓNIMO'],
            ['circuito_id' => 172, 'municipio' => 'SAN JOAQUÍN'],
            ['circuito_id' => 9, 'municipio' => 'SAN JOSÉ'],
            ['circuito_id' => 22, 'municipio' => 'SAN JOSÉ DE FRAGUA'],
            ['circuito_id' => 183, 'municipio' => 'SAN JOSÉ DE LA MONTAÑA'],
            ['circuito_id' => 114, 'municipio' => 'SAN JOSÉ DE MIRANDA'],
            ['circuito_id' => 125, 'municipio' => 'SAN JOSÉ DE PARE'],
            ['circuito_id' => 126, 'municipio' => 'SAN JOSÉ DE URE'],
            ['circuito_id' => 173, 'municipio' => 'SAN JOSÉ DEL GUAVIARE'],
            ['circuito_id' => 40, 'municipio' => 'SAN JOSÉ DEL PALMAR'],
            ['circuito_id' => 58, 'municipio' => 'SAN JUAN BETULIA'],
            ['circuito_id' => 83, 'municipio' => 'SAN JUAN DE ARAMA'],
            ['circuito_id' => 70, 'municipio' => 'SAN JUAN DE RIOSECO'],
            ['circuito_id' => 212, 'municipio' => 'SAN JUAN DE URABÁ'],
            ['circuito_id' => 174, 'municipio' => 'SAN JUAN DEL CESAR'],
            ['circuito_id' => 38, 'municipio' => 'SAN JUAN NEPOMUCENO'],
            ['circuito_id' => 219, 'municipio' => 'SAN JUANITO'],
            ['circuito_id' => 103, 'municipio' => 'SAN LORENZO'],
            ['circuito_id' => 67, 'municipio' => 'SAN LUIS'],
            ['circuito_id' => 79, 'municipio' => 'SAN LUIS DE GACENO'],
            ['circuito_id' => 133, 'municipio' => 'SAN LUIS DE PALENQUE'],
            ['circuito_id' => 175, 'municipio' => 'SAN MARCOS'],
            ['circuito_id' => 3, 'municipio' => 'SAN MARTÍN'],
            ['circuito_id' => 124, 'municipio' => 'SAN MARTÍN DE LOBA'],
            ['circuito_id' => 66, 'municipio' => 'SAN MATEO'],
            ['circuito_id' => 114, 'municipio' => 'SAN MIGUEL'],
            ['circuito_id' => 49, 'municipio' => 'SAN MIGUEL DE SEMA'],
            ['circuito_id' => 194, 'municipio' => 'SAN ONOFRE'],
            ['circuito_id' => 192, 'municipio' => 'SAN PABLO'],
            ['circuito_id' => 49, 'municipio' => 'SAN PABLO DE BORBUR'],
            ['circuito_id' => 58, 'municipio' => 'SAN PEDRO'],
            ['circuito_id' => 103, 'municipio' => 'SAN PEDRO DE CARTAGO'],
            ['circuito_id' => 177, 'municipio' => 'SAN PEDRO DE LOS MILAGROS'],
            ['circuito_id' => 212, 'municipio' => 'SAN PEDRO DE URABÁ'],
            ['circuito_id' => 43, 'municipio' => 'SAN PELAYO'],
            ['circuito_id' => 117, 'municipio' => 'SAN RAFAEL'],
            ['circuito_id' => 55, 'municipio' => 'SAN ROQUE'],
            ['circuito_id' => 27, 'municipio' => 'SAN SEBASTIÁN'],
            ['circuito_id' => 65, 'municipio' => 'SAN SEBASTIÁN DE BUENAVISTA'],
            ['circuito_id' => 163, 'municipio' => 'SAN VICENTE'],
            ['circuito_id' => 178, 'municipio' => 'SAN VICENTE DE CHUCURÍ'],
            ['circuito_id' => 154, 'municipio' => 'SAN VICENTE DEL CAGUÁN'],
            ['circuito_id' => 65, 'municipio' => 'SAN ZENÓN'],
            ['circuito_id' => 137, 'municipio' => 'SANDONÁ'],
            ['circuito_id' => 65, 'municipio' => 'SANTA ANA'],
            ['circuito_id' => 179, 'municipio' => 'SANTA BÁRBARA'],
            ['circuito_id' => 65, 'municipio' => 'SANTA BÁRBARA DE PINTO'],
            ['circuito_id' => 208, 'municipio' => 'SANTA BÁRBARA ISCUANDÉ'],
            ['circuito_id' => 39, 'municipio' => 'SANTA CATALINA'],
            ['circuito_id' => 210, 'municipio' => 'SANTA CRUZ'],
            ['circuito_id' => 217, 'municipio' => 'SANTA HELENA DEL OPÓN'],
            ['circuito_id' => 105, 'municipio' => 'SANTA ISABEL'],
            ['circuito_id' => 167, 'municipio' => 'SANTA LUCÍA'],
            ['circuito_id' => 130, 'municipio' => 'SANTA MARÍA'],
            ['circuito_id' => 111, 'municipio' => 'SANTA MARTA'],
            ['circuito_id' => 27, 'municipio' => 'SANTA ROSA'],
            ['circuito_id' => 182, 'municipio' => 'SANTA ROSA DE CABAL'],
            ['circuito_id' => 39, 'municipio' => 'SANTA ROSA DE LIMA O DEL NORTE'],
            ['circuito_id' => 183, 'municipio' => 'SANTA ROSA DE OSOS'],
            ['circuito_id' => 184, 'municipio' => 'SANTA ROSA DE VITERBO'],
            ['circuito_id' => 192, 'municipio' => 'SANTA ROSA DEL SUR'],
            ['circuito_id' => 151, 'municipio' => 'SANTA ROSALÍA'],
            ['circuito_id' => 125, 'municipio' => 'SANTA SOFÍA'],
            ['circuito_id' => 180, 'municipio' => 'SANTAFÉ DE ANTIOQUIA'],
            ['circuito_id' => 79, 'municipio' => 'SANTAMARÍA'],
            ['circuito_id' => 125, 'municipio' => 'SANTANA'],
            ['circuito_id' => 186, 'municipio' => 'SANTANDER DE QUILICHAO'],
            ['circuito_id' => 59, 'municipio' => 'SANTIAGO'],
            ['circuito_id' => 194, 'municipio' => 'SANTIAGO DE TOLÚ'],
            ['circuito_id' => 55, 'municipio' => 'SANTO DOMINGO'],
            ['circuito_id' => 200, 'municipio' => 'SANTO TOMÁS'],
            ['circuito_id' => 13, 'municipio' => 'SANTUARIO'],
            ['circuito_id' => 210, 'municipio' => 'SAPUYES'],
            ['circuito_id' => 187, 'municipio' => 'SARAVENA'],
            ['circuito_id' => 59, 'municipio' => 'SARDINATA'],
            ['circuito_id' => 220, 'municipio' => 'SASAIMA'],
            ['circuito_id' => 140, 'municipio' => 'SATIVANORTE'],
            ['circuito_id' => 140, 'municipio' => 'SATIVASUR'],
            ['circuito_id' => 188, 'municipio' => 'SEGOVIA'],
            ['circuito_id' => 52, 'municipio' => 'SESQUILÉ'],
            ['circuito_id' => 189, 'municipio' => 'SEVILLA'],
            ['circuito_id' => 209, 'municipio' => 'SIACHOQUE'],
            ['circuito_id' => 195, 'municipio' => 'SIBATÉ'],
            ['circuito_id' => 190, 'municipio' => 'SIBUNDOY'],
            ['circuito_id' => 136, 'municipio' => 'SILOS'],
            ['circuito_id' => 77, 'municipio' => 'SILVANIA'],
            ['circuito_id' => 191, 'municipio' => 'SILVIA'],
            ['circuito_id' => 198, 'municipio' => 'SIMACOTA'],
            ['circuito_id' => 213, 'municipio' => 'SIMIJACA'],
            ['circuito_id' => 192, 'municipio' => 'SIMITÍ'],
            ['circuito_id' => 193, 'municipio' => 'SINCÉ'],
            ['circuito_id' => 203, 'municipio' => 'SINCELEJO'],
            ['circuito_id' => 92, 'municipio' => 'SIPÍ'],
            ['circuito_id' => 53, 'municipio' => 'SITIO NUEVO'],
            ['circuito_id' => 195, 'municipio' => 'SOACHA'],
            ['circuito_id' => 196, 'municipio' => 'SOATÁ'],
            ['circuito_id' => 197, 'municipio' => 'SOCHA'],
            ['circuito_id' => 198, 'municipio' => 'SOCORRO'],
            ['circuito_id' => 197, 'municipio' => 'SOCOTÁ'],
            ['circuito_id' => 199, 'municipio' => 'SOGAMOSO'],
            ['circuito_id' => 71, 'municipio' => 'SOLANO'],
            ['circuito_id' => 200, 'municipio' => 'SOLEDAD'],
            ['circuito_id' => 22, 'municipio' => 'SOLITA'],
            ['circuito_id' => 87, 'municipio' => 'SOMONDOCO'],
            ['circuito_id' => 201, 'municipio' => 'SONSÓN'],
            ['circuito_id' => 202, 'municipio' => 'SOPETRÁN'],
            ['circuito_id' => 39, 'municipio' => 'SOPLAVIENTO'],
            ['circuito_id' => 224, 'municipio' => 'SOPÓ'],
            ['circuito_id' => 209, 'municipio' => 'SORA'],
            ['circuito_id' => 209, 'municipio' => 'SORACÁ'],
            ['circuito_id' => 209, 'municipio' => 'SOTAQUIRÁ'],
            ['circuito_id' => 147, 'municipio' => 'SOTARÁ'],
            ['circuito_id' => 198, 'municipio' => 'SUAITA'],
            ['circuito_id' => 167, 'municipio' => 'SUAN'],
            ['circuito_id' => 186, 'municipio' => 'SUÁREZ'],
            ['circuito_id' => 80, 'municipio' => 'SUAZA'],
            ['circuito_id' => 76, 'municipio' => 'SUBACHOQUE'],
            ['circuito_id' => 138, 'municipio' => 'SUCRE'],
            ['circuito_id' => 52, 'municipio' => 'SUESCA'],
            ['circuito_id' => 134, 'municipio' => 'SUPATÁ'],
            ['circuito_id' => 164, 'municipio' => 'SUPÍA'],
            ['circuito_id' => 29, 'municipio' => 'SURATÁ'],
            ['circuito_id' => 213, 'municipio' => 'SUSA'],
            ['circuito_id' => 196, 'municipio' => 'SUSACÓN'],
            ['circuito_id' => 49, 'municipio' => 'SUTAMARCHÁN'],
            ['circuito_id' => 213, 'municipio' => 'SUTATAUSA'],
            ['circuito_id' => 87, 'municipio' => 'SUTATENZA'],
            ['circuito_id' => 224, 'municipio' => 'TABIO'],
            ['circuito_id' => 92, 'municipio' => 'TADÓ'],
            ['circuito_id' => 124, 'municipio' => 'TALAIGANUEVA'],
            ['circuito_id' => 3, 'municipio' => 'TAMALAMEQUE'],
            ['circuito_id' => 139, 'municipio' => 'TÁMARA'],
            ['circuito_id' => 187, 'municipio' => 'TAME'],
            ['circuito_id' => 204, 'municipio' => 'TÁMESIS'],
            ['circuito_id' => 137, 'municipio' => 'TAMINANGO'],
            ['circuito_id' => 137, 'municipio' => 'TANGUA'],
            ['circuito_id' => 122, 'municipio' => 'TARAIRA'],
            ['circuito_id' => 42, 'municipio' => 'TARAZÁ'],
            ['circuito_id' => 80, 'municipio' => 'TARQUÍ'],
            ['circuito_id' => 95, 'municipio' => 'TARSO'],
            ['circuito_id' => 140, 'municipio' => 'TASCO'],
            ['circuito_id' => 128, 'municipio' => 'TAURAMENA'],
            ['circuito_id' => 213, 'municipio' => 'TAUSA'],
            ['circuito_id' => 130, 'municipio' => 'TELLO'],
            ['circuito_id' => 100, 'municipio' => 'TENA'],
            ['circuito_id' => 146, 'municipio' => 'TENERIFE'],
            ['circuito_id' => 76, 'municipio' => 'TENJO'],
            ['circuito_id' => 87, 'municipio' => 'TENZA'],
            ['circuito_id' => 132, 'municipio' => 'TEORAMA'],
            ['circuito_id' => 130, 'municipio' => 'TERUEL'],
            ['circuito_id' => 102, 'municipio' => 'TESALIA'],
            ['circuito_id' => 77, 'municipio' => 'TIBACUY'],
            ['circuito_id' => 161, 'municipio' => 'TIBANÁ'],
            ['circuito_id' => 63, 'municipio' => 'TIBASOSA'],
            ['circuito_id' => 52, 'municipio' => 'TIBIRITA'],
            ['circuito_id' => 59, 'municipio' => 'TIBÚ'],
            ['circuito_id' => 127, 'municipio' => 'TIERRALTA'],
            ['circuito_id' => 143, 'municipio' => 'TIMANÁ'],
            ['circuito_id' => 147, 'municipio' => 'TIMBÍO'],
            ['circuito_id' => 86, 'municipio' => 'TIMBIQUÍ'],
            ['circuito_id' => 49, 'municipio' => 'TINJACÁ'],
            ['circuito_id' => 196, 'municipio' => 'TIPACOQUE'],
            ['circuito_id' => 110, 'municipio' => 'TIQUISIO'],
            ['circuito_id' => 205, 'municipio' => 'TITIRIBÍ'],
            ['circuito_id' => 209, 'municipio' => 'TOCA'],
            ['circuito_id' => 81, 'municipio' => 'TOCAIMA'],
            ['circuito_id' => 224, 'municipio' => 'TOCANCIPÁ'],
            ['circuito_id' => 125, 'municipio' => 'TOGÜÍ'],
            ['circuito_id' => 183, 'municipio' => 'TOLEDO'],
            ['circuito_id' => 194, 'municipio' => 'TOLÚ VIEJO'],
            ['circuito_id' => 29, 'municipio' => 'TONA'],
            ['circuito_id' => 199, 'municipio' => 'TÓPAGA'],
            ['circuito_id' => 134, 'municipio' => 'TOPAIPÍ'],
            ['circuito_id' => 35, 'municipio' => 'TORIBÍO'],
            ['circuito_id' => 166, 'municipio' => 'TORO'],
            ['circuito_id' => 199, 'municipio' => 'TOTA'],
            ['circuito_id' => 191, 'municipio' => 'TOTORÓ'],
            ['circuito_id' => 133, 'municipio' => 'TRINIDAD'],
            ['circuito_id' => 207, 'municipio' => 'TRUJILLO'],
            ['circuito_id' => 21, 'municipio' => 'TUBARÁ'],
            ['circuito_id' => 48, 'municipio' => 'TUCHÍN'],
            ['circuito_id' => 207, 'municipio' => 'TULUÁ'],
            ['circuito_id' => 208, 'municipio' => 'TUMACO'],
            ['circuito_id' => 28, 'municipio' => 'TUNJA'],
            ['circuito_id' => 49, 'municipio' => 'TUNUNGUÁ'],
            ['circuito_id' => 210, 'municipio' => 'TÚQUERRES'],
            ['circuito_id' => 211, 'municipio' => 'TURBACO'],
            ['circuito_id' => 211, 'municipio' => 'TURBANÁ'],
            ['circuito_id' => 212, 'municipio' => 'TURBO'],
            ['circuito_id' => 209, 'municipio' => 'TURMEQUÉ'],
            ['circuito_id' => 209, 'municipio' => 'TUTA'],
            ['circuito_id' => 184, 'municipio' => 'TUTAZÁ'],
            ['circuito_id' => 78, 'municipio' => 'UBALÁ'],
            ['circuito_id' => 37, 'municipio' => 'UBAQUE'],
            ['circuito_id' => 213, 'municipio' => 'UBATÉ'],
            ['circuito_id' => 40, 'municipio' => 'ULLOA'],
            ['circuito_id' => 79, 'municipio' => 'ÚMBITA '],
            ['circuito_id' => 37, 'municipio' => 'UNE'],
            ['circuito_id' => 164, 'municipio' => 'UNGUÍA'],
            ['circuito_id' => 92, 'municipio' => 'UNIÓN PANAMERICANA'],
            ['circuito_id' => 61, 'municipio' => 'URAMITA'],
            ['circuito_id' => 112, 'municipio' => 'URIBÍA'],
            ['circuito_id' => 214, 'municipio' => 'URRAO'],
            ['circuito_id' => 218, 'municipio' => 'URUMITA'],
            ['circuito_id' => 167, 'municipio' => 'USIACURÍ'],
            ['circuito_id' => 220, 'municipio' => 'ÚTICA'],
            ['circuito_id' => 221, 'municipio' => 'VALDIVIA'],
            ['circuito_id' => 127, 'municipio' => 'VALENCIA'],
            ['circuito_id' => 156, 'municipio' => 'VALLE DE GUAMUEZ'],
            ['circuito_id' => 172, 'municipio' => 'VALLE DE SAN JOSÉ'],
            ['circuito_id' => 90, 'municipio' => 'VALLE DE SAN JUAN'],
            ['circuito_id' => 44, 'municipio' => 'VALLEDUPAR'],
            ['circuito_id' => 204, 'municipio' => 'VALPARAÍSO'],
            ['circuito_id' => 222, 'municipio' => 'VEGACHÍ'],
            ['circuito_id' => 217, 'municipio' => 'VÉLEZ'],
            ['circuito_id' => 105, 'municipio' => 'VENADILLO'],
            ['circuito_id' => 72, 'municipio' => 'VENECIA'],
            ['circuito_id' => 209, 'municipio' => 'VENTAQUEMADA'],
            ['circuito_id' => 220, 'municipio' => 'VERGARA'],
            ['circuito_id' => 166, 'municipio' => 'VERSALLES'],
            ['circuito_id' => 29, 'municipio' => 'VETAS'],
            ['circuito_id' => 70, 'municipio' => 'VIANÍ'],
            ['circuito_id' => 98, 'municipio' => 'VICTORIA'],
            ['circuito_id' => 12, 'municipio' => 'VIGÍA DEL FUERTE'],
            ['circuito_id' => 34, 'municipio' => 'VIJES'],
            ['circuito_id' => 209, 'municipio' => 'VILLA DE LEYVA'],
            ['circuito_id' => 107, 'municipio' => 'VILLA HERMOSA'],
            ['circuito_id' => 186, 'municipio' => 'VILLA RICA'],
            ['circuito_id' => 109, 'municipio' => 'VILLA ROSARIO'],
            ['circuito_id' => 59, 'municipio' => 'VILLACARO'],
            ['circuito_id' => 123, 'municipio' => 'VILLAGARZÓN'],
            ['circuito_id' => 134, 'municipio' => 'VILLAGÓMEZ'],
            ['circuito_id' => 115, 'municipio' => 'VILLAMARÍA'],
            ['circuito_id' => 39, 'municipio' => 'VILLANUEVA'],
            ['circuito_id' => 52, 'municipio' => 'VILLAPINZÓN'],
            ['circuito_id' => 120, 'municipio' => 'VILLAVICENCIO'],
            ['circuito_id' => 130, 'municipio' => 'VILLAVIEJA'],
            ['circuito_id' => 220, 'municipio' => 'VILLETA'],
            ['circuito_id' => 81, 'municipio' => 'VIOTÁ'],
            ['circuito_id' => 161, 'municipio' => 'VIRACACHA'],
            ['circuito_id' => 83, 'municipio' => 'VISTA HERMOSA'],
            ['circuito_id' => 9, 'municipio' => 'VITERBO'],
            ['circuito_id' => 101, 'municipio' => 'YACOPÍ'],
            ['circuito_id' => 137, 'municipio' => 'YACUANQUER'],
            ['circuito_id' => 130, 'municipio' => 'YAGUARA'],
            ['circuito_id' => 222, 'municipio' => 'YALÍ'],
            ['circuito_id' => 221, 'municipio' => 'YARUMAL'],
            ['circuito_id' => 222, 'municipio' => 'YOLOMBÓ'],
            ['circuito_id' => 149, 'municipio' => 'YONDÓ'],
            ['circuito_id' => 223, 'municipio' => 'YOPAL'],
            ['circuito_id' => 31, 'municipio' => 'YOTOCO'],
            ['circuito_id' => 34, 'municipio' => 'YUMBO'],
            ['circuito_id' => 38, 'municipio' => 'ZAMBRANO'],
            ['circuito_id' => 29, 'municipio' => 'ZAPATOCA'],
            ['circuito_id' => 146, 'municipio' => 'ZAPAYÁN'],
            ['circuito_id' => 64, 'municipio' => 'ZARAGOZA'],
            ['circuito_id' => 166, 'municipio' => 'ZARZAL'],
            ['circuito_id' => 121, 'municipio' => 'ZETAQUIRÁ'],
            ['circuito_id' => 70, 'municipio' => 'ZIPACÓN'],
            ['circuito_id' => 224, 'municipio' => 'ZIPAQUIRÁ'],
            ['circuito_id' => 53, 'municipio' => 'ZONA BANANERA'],



        ];
        foreach ($areas as $item) {
            DB::table('juzgmunicipios')->insert([
                'circuito_id' => $item['circuito_id'],
                'municipio' => $item['municipio'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]);
        }
    }
}
